### ISSUE TITLE
Support for Dynamic Groups with DataStore

### ISSUE THREAD

**Issue by jdanielsyeah** [aws-amplify/amplify-category-api#846] opened 2022-10-04 10:52 UTC
### Is this feature request related to a new or existing Amplify category?

auth, storage

### Describe the feature you'd like to request

Could someone please provide clarity as to when/if DataStore will ever be compatible with authorisation for dynamic groups (and also for field-level rules if possible)?

We're currently trying to decide whether to try to continue to utilise DataStore in the anticipation that the functionality will be implemented at some point in the future - or whether best to remove DataStore from our project entirely. It would be a great help if we could get some clarity.

I've seen that Dynamic Groups authorization are currently supported by Amplify with AppSync: 
[User group-based data access](https://docs.amplify.aws/cli/graphql/authorization-rules/#user-group-based-data-access)

They do not currently support subscriptions, although that appears to be on the way, according to this issue/comment:
https://github.com/aws-amplify/amplify-category-api/issues/389#issuecomment-1129359040
(It would be great to get an update on this too!)

### Describe the solution you'd like

Initially, just an update on the current state of play with these features/updates would be great. In the future it would be very useful if the authorisation rules could be utilised with DataStore. I've seen plenty of comments seeking the same.

### Describe alternatives you've considered

Current alternatives appear to be to remove DataStore and use AppSync to update the front-end. Customising resolvers or using Lambdas would likely work, but that's a whole extra lot of work.

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request

### Would this feature include a breaking change?

- [ ] ⚠️ This feature might incur a breaking change

**Comment by josefaidt** [comment] 2022-10-04 18:08
Hey @jdanielsyeah :wave: thanks for raising this! This appears to be a duplicate of the request here https://github.com/aws-amplify/amplify-category-api/issues/389, and is something the team is actively investigating! Closing as a duplicate request, please subscribe to #389 for further updates

**Closed by josefaidt** 2022-10-04 18:08 UTC
Labels: pending-triage, DataStore, pending-review

**Comment by jdanielsyeah** [comment] 2022-10-05 07:02
Hi @josefaidt - thanks for looking at this! Issue #389 seems to have narrowed it's scope to be about AppSync only - as per this comment: https://github.com/aws-amplify/amplify-category-api/issues/389#issuecomment-1129359040

It looks like AppSync has now been updated to work with Dynamic Groups authorisation, but DataStore functionality has not been covered?
