### ISSUE TITLE
"identityPool" authorization for custom mutation

### ISSUE THREAD

**Issue by jewells07** [aws-amplify/amplify-category-api#2635] opened 2024-06-18 18:36 UTC
### Amplify CLI Version

12.12.2

### Question

how can i add "identityPool" in authorization for custom mutation.

``` 
 Mutation:
 
    CreatingUserProfile: a
      .mutation()
      .arguments({
        owner: a.string().required(),
        firstName: a.string().required(),
        lastName: a.string().required(),
        email: a.email().required(),
        birthdate: a.datetime().required(),
        location: a.string(),
      })
      .returns(a.ref('UserProfile'))
      .handler([
        a.handler.custom({
          entry: './userProfile/createUserProfile.js',
          dataSource: a.ref('UserProfile'),
        }),
      ])
      .authorization((allow) => [allow.authenticated('identityPool')]),
```
It shows the error:
```
identityPool-based auth (allow.guest() and allow.authenticated('identityPool')) is not supported with a.handler.custom
Caused By: identityPool-based auth (allow.guest() and allow.authenticated('identityPool')) is not supported with a.handler.custom

Resolution: Check your data schema definition for syntax and type errors.
```

**Comment by chrisbonifacio** [comment] 2024-06-19 18:43
Hi @jewells07 thanks for raising this issue 👋 

I was able to reproduce the error with the following schema:

```ts
UserProfile: a
    .model({
      owner: a.string().required(),
      firstName: a.string().required(),
      lastName: a.string().required(),
      email: a.email().required(),
      birthdate: a.datetime().required(),
      location: a.string(),
    })
    .authorization((allow) => [allow.authenticated("identityPool")]),
  CreatingUserProfile: a
    .mutation()
    .arguments({
      owner: a.string().required(),
      firstName: a.string().required(),
      lastName: a.string().required(),
      email: a.email().required(),
      birthdate: a.datetime().required(),
      location: a.string(),
    })
    .returns(a.ref("UserProfile"))
    .handler([
      a.handler.custom({
        entry: "./userProfile/createUserProfile.js",
        dataSource: a.ref("UserProfile"),
      }),
    ])
    .authorization((allow) => [allow.authenticated("identityPool")]),
```

Error

![CleanShot 2024-06-19 at 14 39 50@2x](https://github.com/aws-amplify/amplify-category-api/assets/16952986/4576da8d-b7bc-4431-b295-bc64095c4eac)

This seems to be expected behavior according to the error message but I will reach out to the team to confirm.
In the meantime, can you please clarify your use case and how you intend to use identityPool as an auth rule?

**Comment by jewells07** [comment] 2024-06-19 19:27
I was trying to hit this mutation from the function when the user signed up successfully. and I don't want any user to use this mutation. even i'm not able to do this ```.authorization((allow) => [allow.authenticated().to(['create'])]) ```.

**Comment by naedx** [comment] 2024-06-20 15:01
I also encountered this issue with the same use case. I have a custom mutation that I don't want to be accessible except by a lambda function that I want to authorize with IAM.

**Comment by chrisbonifacio** [comment] 2024-06-24 14:41
After reaching out to the team, it was confirmed that this is expected behavior. It's currently not possible to create a custom resolver when using IAM as the default auth mode. It's also not possible to specifically allow `iam`.

I think you need to grant the lambda access to mutations using `allow.resource` on the schema like so:

```ts
const schema = a
  .schema({
    // ...
  })
  .authorization((allow) => allow.resource(postConfirmationTriggerLambda));
```

Or from the `backend.ts` file:

```ts
import { defineBackend } from "@aws-amplify/backend";
import { auth } from "./auth/resource";
import { data } from "./data/resource";
import { postConfirmationTriggerLambda } from "./auth/triggers/post-confirmation/resource";

const backend = defineBackend({
  auth,
  data,
  postConfirmationTriggerLambda,
});

backend.data.resources.graphqlApi.grantMutation(
  backend.postConfirmationTriggerLambda.resources.lambda
);
```

I'll close this issue as this is not a bug but still please let us know if you run into issues authorizing the lambda

**Closed** 2024-06-24 14:41 UTC
Labels: question, data-schema

**Comment by OperationalFallacy** [comment] 2024-08-03 03:45
> After reaching out to the team, it was confirmed that this is expected behavior. It's currently not possible to create a custom 
> I'll close this issue as this is not a bug but still please let us know if you run into issues authorizing the lambda

Can you elaborate why this is expected?

> need to grant the lambda access to mutations using allow.resource

Mutations with custom handlers do not work with Lambda functions (or event bridge). This grant doesn't change behavior of appsync.

Only front-end authenticated users can use these mutations, with authorization set to `allow.authenticated()`

**Comment by OperationalFallacy** [comment] 2024-08-03 16:47
So this error comes from @aws-amplify/data-schema packages which is from https://github.com/aws-amplify/amplify-api-next repository - that that repo is private for some reason

I think there is an easy workaround

`validateCustomHandlerAuthRule` function throw this error. It has a condition which doesn't make sense, it prevents iam auth on custom resolvers. Looking at the commented code, again the question to Amplify team what it means, "not supported"?

To fix it, monkey patch SchemaProcessor.js and comment out exception. The IAM auth then works just fine. the graphql schema gets generated with correct auth method

```
type Mutation {
  publishChatMsg(threadId: ID!, status: String!, message: String!, owner: String!): MessageStatusChange @aws_iam
```

node_modules/@aws-amplify/data-schema/dist/cjs/SchemaProcessor.js
```
function validateCustomHandlerAuthRule(rule: AuthRule) {
  if (rule.groups && rule.provider === 'oidc') {
    throw new Error('OIDC group auth is not supported with a.handler.custom');
  }

  // not currently supported with handler.custom (JS Resolvers), but will be in the future
  if (rule.provider === 'identityPool' || (rule.provider as string) === 'iam') {
    console.debug("Silly amplify can not figure out provider:", rule.provider)
    throw new Error(
      "identityPool-based auth (allow.guest() and allow.authenticated('identityPool')) is not supported with a.handler.custom",
    );
  }
}
```

**Comment by nam-truong-le** [comment] 2024-10-31 14:15
> After reaching out to the team, it was confirmed that this is expected behavior. It's currently not possible to create a custom resolver when using IAM as the default auth mode. It's also not possible to specifically allow `iam`.
> 
> I think you need to grant the lambda access to mutations using `allow.resource` on the schema like so:
> 
> ```ts
> const schema = a
>   .schema({
>     // ...
>   })
>   .authorization((allow) => allow.resource(postConfirmationTriggerLambda));
> ```
> 
> Or from the `backend.ts` file:
> 
> ```ts
> import { defineBackend } from "@aws-amplify/backend";
> import { auth } from "./auth/resource";
> import { data } from "./data/resource";
> import { postConfirmationTriggerLambda } from "./auth/triggers/post-confirmation/resource";
> 
> const backend = defineBackend({
>   auth,
>   data,
>   postConfirmationTriggerLambda,
> });
> 
> backend.data.resources.graphqlApi.grantMutation(
>   backend.postConfirmationTriggerLambda.resources.lambda
> );
> ```
> 
> I'll close this issue as this is not a bug but still please let us know if you run into issues authorizing the lambda

I tried and both solutions don't work. Lambda got unauthenticated error when executing the graphql custom mutation.

**Comment by shmoon0814** [comment] 2024-12-13 06:12
This is a must-have for environments that want to add a Javascript Resolver that uses the Aurora Data API.

**Comment by AstralBaby** [comment] 2025-02-14 20:58
It is currently not possible to grant access only to lambdas.
