### ISSUE TITLE
amplify push errors - DDB tables with SSESpecification drift

### ISSUE THREAD

**Issue by lewisdonovan** [aws-amplify/amplify-category-api#973] opened 2022-11-09 07:22 UTC
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/dev/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

16.0.0

### Amplify CLI Version

10.4.0

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No

### Amplify Categories

api

### Amplify Commands

push

### Describe the bug

I can't `amplify push` anything to my environment, I'm getting one of a variety of errors each time:

```
🛑 The following resources failed to deploy:
🛑 Resource is not in the state stackUpdateComplete
```
or
```
UPDATE_COMPLETE    GraphQLAPITransformerSchema3CB2AE18 AWS::AppSync::GraphQLSchema Tue Nov 08 2022 21:14:45 GMT-0500 (Eastern Standard Time) 
UPDATE_IN_PROGRESS GraphQLAPITransformerSchema3CB2AE18 AWS::AppSync::GraphQLSchema Tue Nov 08 2022 21:13:42 GMT-0500 (Eastern Standard Time) 
⠴ Rolling back (2 of 1)🛑 An error occurred during the push operation: /
["Index: 0 State: {\"deploy\":\"waitingForDeployment\"} Message: Resource is not in the state stackUpdateComplete"]
```
or my personal favourite:
```
Deployment completed.
Deploying api myApiName [ =--------------------------------------- ] 1/34
        GraphQLAPITransformerSchema3C… AWS::AppSync::GraphQLSchema    UPDATE_IN_PROGRESS             Wed Nov 09 2022 02:05:39…     

Rolled back (2 of 1)
🛑 ["Index: 0 State: {\"deploy\":\"waitingForDeployment\"} Message: Resource is not in the state stackUpdateComplete"]
```
They all seem to pertain to the GraphQL API. At one point, the CLI was helpful enough to give me a list of affected tables:
```
Deploying api myApiName [ =====----------------------------------- ] 4/34
        GraphQLAPIDefaultApiKey215A6D… AWS::AppSync::ApiKey           UPDATE_COMPLETE                Tue Nov 08 2022 20:42:37…     
        GraphQLAPITransformerSchema3C… AWS::AppSync::GraphQLSchema    UPDATE_COMPLETE                Tue Nov 08 2022 20:43:39…     
        ActiveSubscription             AWS::CloudFormation::Stack     UPDATE_COMPLETE                Tue Nov 08 2022 20:44:02…     
        FunctionDirectiveStack         AWS::CloudFormation::Stack     UPDATE_COMPLETE                Tue Nov 08 2022 20:44:03…     
        Podcast                        AWS::CloudFormation::Stack     UPDATE_FAILED                  Tue Nov 08 2022 20:41:17…     
        Size                           AWS::CloudFormation::Stack     UPDATE_FAILED                  Tue Nov 08 2022 20:41:28…     
        FeaturedContent                AWS::CloudFormation::Stack     UPDATE_FAILED                  Tue Nov 08 2022 20:41:28…     
        AudioRoom                      AWS::CloudFormation::Stack     UPDATE_FAILED                  Tue Nov 08 2022 20:41:17…     
        Product                        AWS::CloudFormation::Stack     UPDATE_FAILED                  Tue Nov 08 2022 20:41:17…     
        Artist                         AWS::CloudFormation::Stack     UPDATE_FAILED                  Tue Nov 08 2022 20:41:28…     
        SubscriptionTier               AWS::CloudFormation::Stack     UPDATE_FAILED                  Tue Nov 08 2022 20:41:28…     
        PodcastEpisode                 AWS::CloudFormation::Stack     UPDATE_FAILED                  Tue Nov 08 2022 20:41:18…     
```
But on subsequent pushes it reverted back to one of the other errors above. I've tried `amplify push --iterative-rollback` but it doesn't seem to do anything. I've also tried `--force` and `--allow-destructive-graphql-schema-updates`, but nothing seems to make a difference.

I checked the CloudFormation stack and noticed I'm getting stack drift on some of my DynamoDB tables where the following object has been removed from the  expected object:
```
"SSESpecification": {
    "SSEEnabled": false
  }
```
It hasn't been changed to true it's just been removed altogether. I've tried updating one of the tables via the CLI using `dynamodb update-table --table-name "Size-znobspoa4jawhdbz6ayrnqt34a-cgsdummy" --sse-specification Enabled=false` but it returns the following error:
```
An error occurred (ValidationException) when calling the UpdateTable operation: One or more parameter values were invalid: Table is already encrypted by default
```
I've also tried looking through the table's settings in the console, but I can't find any way to set encryption to `false`. 

Any help greatly appreciated.

### Expected behavior

Being able to push

### Reproduction steps

1. `amplify push`
2. Wait for like 15 minutes
3. False hope
4. Cry

### GraphQL schema(s)

I don't want to paste my full schema here, I'm happy to send it privately. Please advise how/where.
<details>

```graphql
# Put schemas below this line


```

</details>

### Project Identifier

I submitted a report (twice) but didn't get a project identifier 🤷🏻‍♂️

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by sundersc** [comment] 2022-11-09 17:56
@lewisdonovan - Thank you for raising this issue. I'm trying to reproduce the error by creating a project with older version of CLI and upgrade to 10.4.0 to see if this is caused by CLI upgrade.

Meanwhile, could you send the `amplify` folder to amplify-cli@amazon.com? Also, have you tried with older version of CLI (like 10.0.0)?

**Comment by lewisdonovan** [comment] 2022-11-10 06:02
Thanks for getting back. We ended up just creating a new env and binning the old one. We're fortunate enough to be pre-production so we could afford downtime and data loss (it was just dummy data in the DB), although I'm now seriously concerned about the production-readiness of Amplify.

**Comment by josefaidt** [comment] 2022-11-15 19:44
Hey @lewisdonovan thanks for clarifying! Sorry to hear of the rough experience :/ Can you recall which changes were made to the schema or resources prior to the failed push attempt? You've mentioned a variety of errors on push, which some are documented separately here on GitHub, but I'm curious about the `SSESpecification` block you noticed getting removed from the CFN templates (and potentially the source of the drift?)

**Comment by lewisdonovan** [comment] 2022-11-15 19:58
@josefaidt Yeah to be honest this has happened so many times with so little feedback I've given up on diagnosis altogether. The `SSESpecification` thing happened again yesterday on about half of my tables while I was pushing a Lambda update, the schema hadn't been touched.

Now I tend to go through a series of steps and one of them will usually kick the thing back into action. It's never clear which one though.

I've written about them in [this SO comment](https://stackoverflow.com/a/74440688/7546845) and will probably be fashioning a real fun Medium article about it once this project is done.

**Comment by phani-srikar** [comment] 2022-12-01 02:26
Hi @lewisdonovan, can you please check the stack events in your AWS Cloudformation console when you deploy your stack and tell us the more specific error message?
I've scanned the code base to check the instances where this could be possible. There is a [method](https://github.com/aws-amplify/amplify-category-api/blob/5a7ec70b0be45f188397746814a9d02752593141/packages/graphql-transformer-core/src/util/amplifyUtils.ts#L582) that removes the SSE specification, that gets triggered during the migration of V1 to V2 transformers. Can you check your `amplify/api/<api_name>/transform.conf.json` file and see if there are any migration related flags set?

**Comment by lewisdonovan** [comment] 2022-12-06 13:40
@phani-srikar I don't have a `transform.conf` in my API folder, although I just received this error again, log output below:

```bash
Deploying api my-api-name [ ===================================----- ] 33/38
        SearchableStack                AWS::CloudFormation::Stack     UPDATE_FAILED                  Tue Dec 06 2022 08:29:21…     
        ConnectionStack                AWS::CloudFormation::Stack     UPDATE_FAILED                  Tue Dec 06 2022 08:29:22…     
Deployed auth my-auth-name [ ======================================== ] 12/12
        UserPool                       AWS::Cognito::UserPool         UPDATE_COMPLETE                Tue Dec 06 2022 08:29:49…     
Deployed auth userPoolGroups [ ======================================== ] 10/10

🛑 The following resources failed to deploy:
🛑 Resource is not in the state stackUpdateComplete

Learn more at: https://docs.amplify.aws/cli/project/troubleshooting/
```

I'm getting stack drift on one of my tables, it's expecting:
```json
...
  "SSESpecification": {
    "SSEEnabled": false
  }
...
```

But the `SSESpecification` is missing completely.

**Comment by phani-srikar** [comment] 2022-12-06 18:18
Hi @lewisdonovan, I am trying to get you unblocked since I cannot reproduce the issue on my end. Can you try using the **overrides** functionality of CLI to explicitly set the `SSESpecification` on the tables that are failing? You can find the guide [here](https://docs.amplify.aws/cli/graphql/override/#customize-amplify-generated-resources-for-model-directive).

**Comment by lewisdonovan** [comment] 2022-12-06 19:27
@phani-srikar we're no longer blocked, so I'm not gonna add an override at this point. Just trying to assist you guys in finding the problem because it's a really weird and critical bug. 

The workaround I've found is to open `amplify/backend/api/${my_api_name}/parameters.json` and change the `DynamoDBEnableServerSideEncryption` setting from `false` to `true`, save it, then run `amplify push`. The build fails but then I just reverse the change (set it back to `false`), save it, push again and then it works 🤷🏻‍♂️

**Comment by ibrahimcanbaz** [comment] 2023-02-16 19:19
@lewisdonovan i have the same problem, i tried this but not worked 😞 .

**Comment by alharris-at** [comment] 2023-05-25 22:39
@ibrahimcanbaz - if you're still seeing this issue, could you provide your version of amplify cli, and run `amplify diagnose` and provide us w/ that diagnostic id? That should help reproduce this issue.

**Comment by AnilMaktala** [comment] 2023-06-16 14:03
Hi 👋, We are closing this issue as we have not received any response from you. However, if you are still facing the same issue and require our assistance, please don't hesitate to leave a comment and provide us with the information our team had previously asked for. This way, we can reopen the issue and provide you with better assistance.

Thank you!

**Closed** 2023-06-17 21:01 UTC
Labels: p2, pending-response, transferred, ops-deploy
