### ISSUE TITLE
TTL error when trying to Disable Conflict Resolution

### ISSUE THREAD

**Issue by sawakaga** [aws-amplify/amplify-category-api#1480] opened 2023-05-18 15:23 UTC
### Amplify CLI Version

amplify push api -y

### Question

Application were running without any problem at first when Conflict Resolution disabled. After that for experiment I enable the conflict resolution with Auto-Merge mode. When Trying to disable again it gives error as **"Resource handler returned message: "Invalid request provided: AttributeName property of TimeToLiveSpecification is required when TTL status is enabled or while enabling/disabling TTL."**

I am pretty sure, I did not change any configuration related to this via console or Cloud Formation. 

**What I tried**

- amplify update api -> conflict resolution mode -> optimistic -> disable it 
- Deleting table that gives error then try again ( Gives error on the next table) ( All tables have same problem )
- Deleting TimeToLive configuration from **amplify/backend/api/****/build/stacks**
-   ![Checking Drift on the stack error happens](https://github.com/aws-amplify/amplify-category-api/assets/17532486/a7ed9679-8db4-49d1-9040-fae362507b65)
- - Except SSE part it was the same. Still error was TTL related

Now, I did **amplify pull env --restore**

Thank you in advance.

**Comment by josefaidt** [comment] 2023-05-19 18:33
Hey @sawakaga :wave: thanks for raising this! I was able to reproduce this issue using the following steps:

1. `amplify init -y`
2. `amplify add api` > GraphQL > accept defaults
3. `amplify push -y`
4. `amplify update api` > GraphQL > Enable conflict resolution > Auto-merge
5. `amplify push -y`
6. `amplify update api` > GraphQL > Disable conflict resolution
7. `amplify push -y`
8. observe error

```
Deployment failed.
Deploying root stack 1480 [ ---------------------------------------- ] 0/2
	amplify-1480-dev-104958        AWS::CloudFormation::Stack     UPDATE_ROLLBACK_COMPLETE_CLEA… Fri May 19 2023 
	api1480                        AWS::CloudFormation::Stack     UPDATE_FAILED                  Fri May 19 2023 
Deploying api 1480 [ =============--------------------------- ] 2/6
	GraphQLAPIDefaultApiKey215A6D… AWS::AppSync::ApiKey           UPDATE_COMPLETE                Fri May 19 2023 
	GraphQLAPITransformerSchema3C… AWS::AppSync::GraphQLSchema    UPDATE_COMPLETE                Fri May 19 2023 
	Todo                           AWS::CloudFormation::Stack     UPDATE_FAILED                  Fri May 19 2023 

🛑 The following resources failed to deploy:
Resource Name: TodoTable (AWS::DynamoDB::Table)
Event Type: update
Reason: Resource handler returned message: "Invalid request provided: AttributeName property of TimeToLiveSpecification is required when TTL status is enabled or while enabling/disabling TTL." (RequestToken: ff7ab577-061c-b252-9fe4-aabbd948e6b2, HandlerErrorCode: InvalidRequest)
URL: https://console.aws.amazon.com/cloudformation/home?region=us-east-1#/stacks/arn%3Aaws%3Acloudformation%3Aus-east-1%3A814763596509%3Astack%2Famplify-1480-dev-104958-api1480-2XRAKKHBPW99-Todo-1O1HQDMFA3SB%2Faf7bfff0-f671-11ed-9343-1229052f1d65/events


🛑 Resource is not in the state stackUpdateComplete
Name: TodoTable (AWS::DynamoDB::Table), Event Type: update, Reason: Resource handler returned message: "Invalid request provided: AttributeName property of TimeToLiveSpecification is required when TTL status is enabled or while enabling/disabling TTL." (RequestToken: ff7ab577-061c-b252-9fe4-aabbd948e6b2, HandlerErrorCode: InvalidRequest), IsCustomResource: false


Learn more at: https://docs.amplify.aws/cli/project/troubleshooting/

Session Identifier: 0d8bd31d-0a26-460a-b343-09bae7373bd3
```

Marking as a bug

**Comment by ankitjena** [comment] 2023-05-22 09:03
Hey @josefaidt , also facing this issue. Is there a way to disable conflict resolution from the UI. Couldn't find anything on the docs. Would be super helpful.

**Comment by phani-srikar** [comment] 2023-05-22 21:15
We have a fix for this in-flight. We'll let you know when it's release with Amplify CLI.

**Comment by alharris-at** [comment] 2023-05-23 17:29
Until the CLI has released a patch to work around this. You can mitigate by executing the following steps.

1. Execute `amplify api override` - this will create a new `override.ts` file within the `api` directory of your backend, that you can use to customize the generated CDK constructs.
2. Within the `override.ts` file, perform something like the following code snippet.

```typescript
export function override(resources: AmplifyApiGraphQlResourceStackTemplate, amplifyProjectInfo: AmplifyProjectInfo) {
  Object.values(resources.models).forEach(model => model.modelDDBTable.timeToLiveSpecification= {
    attributeName: '_ttl', // Using _ttl is important, so it matches what Amplify is generating when conflict resolution is enabled.
    enabled: false,
  });
}
```

This will leave a ttl _configured_, but _disabled_ on the table.

Please make sure you verify behavior in a `dev` environment before moving to production with something like this.

Also worth noting that if you wish to re-enable the ttl in the future, you'll need to remove the overridden code.

**Comment by alharris-at** [comment] 2023-05-23 18:23
I've engaged the dynamodb team to work on a fix to mitigate this impact for all customers. We'll update this ticket when the manual workarounds can be removed from Amplify projects.

**Comment by ankitjena** [comment] 2023-05-23 19:51
@alharris-at thanks for quick response, tried this out in dev environment. Though since need was urgent to launch the product, i dropped and recreated the prod tables from the UI 😅

**Comment by alharris-at** [comment] 2023-05-23 20:37
Got it - sorry to hear about that. PDX should have this issue resolved now, with remaining regions becoming unblocked over the next several hours.

**Comment by alharris-at** [comment] 2023-05-23 23:31
This issue should be mitigated in all regions. Closing out this issue now.

**Closed by alharris-at** 2023-05-23 23:31 UTC
Labels: bug, p1, api-graphql
