### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by AnilMaktala** [aws-amplify/amplify-category-api#2209] opened 2024-01-22 17:44 UTC
### Amplify CLI Version

0.9.3

### What operating system are you using?

macOS 14.2.1

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.
<details>

System:
    OS: macOS 14.2.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 47.08 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.18.2 - ~/.nvm/versions/node/v18.18.2/bin/node
    Yarn: 1.22.21 - ~/.nvm/versions/node/v18.18.2/bin/yarn
    npm: 9.8.1 - ~/.nvm/versions/node/v18.18.2/bin/npm
    pnpm: 8.10.5 - ~/.nvm/versions/node/v18.18.2/bin/pnpm
    bun: 1.0.0 - ~/.bun/bin/bun
    Watchman: Not Found
  npmPackages:
    @aws-amplify/backend: ^0.8.0 => 0.8.0 
    @aws-amplify/backend-cli: ^0.9.3 => 0.9.3 
    aws-amplify: ^6.0.6 => 6.0.7 
    aws-cdk: 2.110.1 => 2.110.1 
    aws-cdk-lib: ^2.110.1 => 2.110.1 
    typescript: ^5.3.3 => 5.3.3

</details>

### Describe the bug

Please I got this error after adding three new models to my schema. when I take 2 out of the 3 I added. it works fine. is there a limit to how many models I can deploy?

here's a screenshot of my schema
https://photos.app.goo.gl/1AaYC4uZnT4hBLq59

the models added are QuizStudent, QuizSubject. QuizGrade

this is a major blocker for me and I will be unable to proceed if there is truly a limit. this is already the second major blocker and might have to restructure the entire backend 
![image](https://github.com/aws-amplify/amplify-category-api/assets/3206171/36da6175-8e4f-4d0c-958e-b9c84014e7fc)

### Expected behavior

should deploy the app without any error

### Reproduction steps
```js
const schema = a.schema({
  Institution: a
    .model({
      id: a.string().required(),
      name: a.string().required(),
      teachers: a.hasMany('Teacher'),
      stats: a.hasMany('Stats'),
    })
    .authorization([
      a.allow.specificGroup(UserGroup.SUPERADMIN),
      a.allow.groupDefinedIn('adminRole').to(['read']),
      a.allow.groupDefinedIn('teacherRole').to(['read']),
      a.allow.groupDefinedIn('studentRole').to(['read']),
    ]),
  Profile: a
    .model({
      firstName: a.string().required(),
      lastName: a.string().required(),
      bio: a.string(),
      profileImage: a.url(),
    })
    .authorization([
      a.allow.specificGroup(UserGroup.SUPERADMIN),
      a.allow.owner().inField('id').to(['read', 'update', 'create']),
      a.allow.groupDefinedIn('adminRole'),
      a.allow.groupDefinedIn('teacherRole').to(['read', 'create', 'update']),
      a.allow.groupDefinedIn('studentRole').to(['read']),
    ]),
  Avatar: a
    .model({
      face: a.url(),
      full: a.url().required(),
    })
    .authorization([a.allow.public(), a.allow.private()]),
  Student: a
    .model({
      grade: a
        .hasOne('Grade')
        .authorization([
          a.allow.specificGroup(UserGroup.SUPERADMIN),
          a.allow.groupDefinedIn('adminRole'),
          a.allow
            .groupDefinedIn('teacherRole')
            .to(['read', 'create', 'update']),
          a.allow.groupDefinedIn('studentRole').to(['read']),
        ]),
      avatar: a.hasOne('Avatar'),
      primaryLanguage: a.hasOne('Language'),
      secondaryLanguage: a.hasOne('Language'),
      profile: a.hasOne('Profile'),
      onBoarded: a.boolean().default(false),
    })
    .authorization([
      a.allow.specificGroup(UserGroup.SUPERADMIN),
      a.allow.groupDefinedIn('adminRole'),
      a.allow.groupDefinedIn('teacherRole').to(['read', 'create', 'update']),
      a.allow.groupDefinedIn('studentRole').to(['read']),
      a.allow.owner().to(['read', 'update']),
    ]),
  Teacher: a
    .model({
      subject: a.string(),
      profile: a.hasOne('Profile'),
      institution: a.belongsTo('Institution'),
    })
    .authorization([
      a.allow.specificGroup(UserGroup.SUPERADMIN),
      a.allow.groupDefinedIn('adminRole'),
      a.allow.groupDefinedIn('teacherRole').to(['read']),
      a.allow.groupDefinedIn('studentRole').to(['read']),
    ]),
  Stats: a
    .model({
      key: a.string().required(),
      value: a.integer().required(),
      time: a.datetime().required(),
      institution: a.belongsTo('Institution'),
    })
    .authorization([
      a.allow.specificGroup(UserGroup.SUPERADMIN),
      a.allow.groupDefinedIn('adminRole').to(['read']),
      a.allow.groupDefinedIn('teacherRole').to(['read']),
      a.allow.groupDefinedIn('studentRole').to(['read']),
    ])
    .identifier(['key', 'time']),
  Subject: a
    .model({
      name: a.string().required(),
      key: a.string().required(),
    })
    .authorization([
      a.allow.specificGroup(UserGroup.SUPERADMIN),
      a.allow
        .specificGroups([UserGroup.ADMIN, UserGroup.TEACHER, UserGroup.STUDENT])
        .to(['read']),
    ]),
  Grade: a
    .model({
      name: a.string().required(),
      key: a.string().required(),
    })
    .authorization([
      a.allow.specificGroup(UserGroup.SUPERADMIN),
      a.allow
        .specificGroups([UserGroup.ADMIN, UserGroup.TEACHER, UserGroup.STUDENT])
        .to(['read']),
    ]),
  Language: a
    .model({
      name: a.string().required(),
      shortName: a.string().required(),
      tagLine: a.string().required(),
      flag: a.url().required(),
    })
    .authorization([
      a.allow.specificGroup(UserGroup.SUPERADMIN),
      a.allow
        .specificGroups([UserGroup.ADMIN, UserGroup.TEACHER, UserGroup.STUDENT])
        .to(['read']),
    ]),
  ComplexityType: a.enum(['EASY', 'MODERATE', 'DIFFICULT']),
  Question: a
    .model({
      excerpt: a.string().required(),
      complexity: a.ref('ComplexityType').required(),
      topic: a.string().required(),
      grade: a.hasOne('Grade').required(),
      subject: a.hasOne('Subject').required(),
      languages: a.hasMany('QuestionLanguage'),
    })
    .authorization([
      a.allow.specificGroup(UserGroup.SUPERADMIN),
      a.allow
        .specificGroups([UserGroup.ADMIN, UserGroup.TEACHER, UserGroup.STUDENT])
        .to(['read']),
    ]),
  QuestionLanguage: a
    .model({
      content: a.json().required(),
      imageContent: a.url(),
      correctOptionValue: a.integer(),
      optionValues: a
        .string()
        .array()
        .authorization([
          a.allow.specificGroup(UserGroup.SUPERADMIN),
          a.allow
            .specificGroups([UserGroup.ADMIN, UserGroup.STUDENT])
            .to(['read']),
        ]),
      question: a.belongsTo('Question'),
      language: a.hasOne('Language'),
    })
    .authorization([
      a.allow.specificGroup(UserGroup.SUPERADMIN),
      a.allow
        .specificGroups([UserGroup.ADMIN, UserGroup.TEACHER, UserGroup.STUDENT])
        .to(['read']),
    ]),
  Quiz: a
    .model({
      id: a.id().required(),
      title: a.string().required(),
      noOfQuestions: a.integer().default(0).required(),
      institution: a.id().required(),
      open: a.boolean().default(true),
      grades: a.hasMany('QuizGrade'),
      subjects: a.hasMany('QuizSubject'),
      students: a.hasMany('QuizStudent'),
      questions: a.hasMany('QuizQuestion'),
    })
    .authorization([
      a.allow.specificGroup(UserGroup.SUPERADMIN),
      a.allow.specificGroup(UserGroup.TEACHER).to(['create', 'read']),
      a.allow.owner().to(['create', 'update']),
      a.allow.specificGroup(UserGroup.STUDENT).to(['read']),
    ]),
  QuizGrade: a
    .model({
      grade: a.hasOne('Grade'),
      quiz: a.belongsTo('Quiz'),
    })
    .authorization([
      a.allow.specificGroup(UserGroup.SUPERADMIN),
      a.allow.specificGroup(UserGroup.TEACHER).to(['create', 'read']),
      a.allow.owner().to(['create', 'update']),
      a.allow.specificGroup(UserGroup.STUDENT).to(['read']),
    ]),
  QuizSubject: a
    .model({
      subject: a.hasOne('Subject'),
      quiz: a.belongsTo('Quiz'),
    })
    .authorization([
      a.allow.specificGroup(UserGroup.SUPERADMIN),
      a.allow.specificGroup(UserGroup.TEACHER).to(['create', 'read']),
      a.allow.owner().to(['create', 'update']),
      a.allow.specificGroup(UserGroup.STUDENT).to(['read']),
    ]),
  QuizStudent: a
    .model({
      student: a.hasOne('Student'),
      quiz: a.belongsTo('Quiz'),
    })
    .authorization([
      a.allow.specificGroup(UserGroup.SUPERADMIN),
      a.allow.specificGroup(UserGroup.TEACHER).to(['create', 'read']),
      a.allow.owner().to(['create', 'update']),
    ]),
  QuizQuestion: a
    .model({
      quiz: a.belongsTo('Quiz'),
      question: a.hasOne('Question'),
      defaultLanguage: a.string().required(),
    })
    .authorization([
      a.allow.specificGroup(UserGroup.SUPERADMIN),
      a.allow.specificGroup(UserGroup.TEACHER).to(['create', 'read']),
      a.allow.owner().to(['create', 'update']),
      a.allow.specificGroups([UserGroup.STUDENT, UserGroup.ADMIN]).to(['read']),
    ]),
  CreateUserResponse: a.customType({
    id: a
      .string()
      .required()
      .authorization([
        a.allow.specificGroups([
          UserGroup.SUPERADMIN,
          UserGroup.ADMIN,
          UserGroup.TEACHER,
        ]),
      ]),
  }),
  ApiBaseResponse: a.customType({
    success: a
      .boolean()
      .authorization([a.allow.specificGroup(UserGroup.SUPERADMIN)]),
  }),
  createInstitutionGroups: a
    .mutation()
    .arguments({ institution: a.string().required() })
    .returns(a.ref('ApiBaseResponse'))
    .function('adminActions')
    .authorization([a.allow.specificGroup(UserGroup.SUPERADMIN)]),
  createUser: a
    .mutation()
    .arguments({
      email: a.string().required(),
      password: a.string().required(),
      group: a.string().required(),
      institution: a.string(),
    })
    .returns(a.ref('CreateUserResponse'))
    .function('adminActions')
    .authorization([
      a.allow.specificGroups([
        UserGroup.SUPERADMIN,
        UserGroup.ADMIN,
        UserGroup.TEACHER,
      ]),
    ]),
  CreateQuestionsResponse: a.customType({
    questionsCreated: a.integer().required().authorization([a.allow.private()]),
  }),
  createQuestions: a
    .mutation()
    .arguments({ file: a.url().required() })
    .returns(a.ref('CreateQuestionsResponse'))
    .function('adminActions')
    .authorization([a.allow.specificGroup(UserGroup.SUPERADMIN)]),
});
```

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by phani-srikar** [comment] 2024-01-22 18:29
Possible duplicate of https://github.com/aws-amplify/amplify-category-api/issues/1978

**Comment by phani-srikar** [comment] 2024-01-30 23:42
Please upgrade the Data Construct in your Gen 2 project using `npm i --package-lock-only @aws-amplify/data-construct`. This should add the latest version `1.5.5` of that package which contains the fix.

**Closed** 2024-02-05 20:11 UTC
Labels: bug, cdk-constructs, Gen 2
