### ISSUE TITLE
Owner filter not possible with GraphQl query

### ISSUE THREAD

**Issue by jerocosio** [aws-amplify/amplify-category-api#523] opened 2022-06-08 21:26 UTC
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v14.19.2

### Amplify CLI Version

8.4.0

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

Deployed the generated GraphQl fro de schema.

### Amplify Categories

api

### Amplify Commands

Not applicable

### Describe the bug

I'm receiving an error when trying to filter a graphql call with the owner variable.
I created a model as follows:
``` graphql
type TestModel
  @model(subscriptions: null)
  @auth(
    rules: [
      { allow: owner, operations: [read, create] }
      { allow: groups, groups: ["Admin"] }
    ]
  ) {
  id: ID!
  title: String!
}
```
But when I try to make a graphql to get the items and filtering them by the owner:
``` javascript
const { data } = await API.graphql({
      query: listTestModel,
      variables: {
        filter: {
          owner: {
            eq: 'actualusername,
          },
        },
      },
    });
```

I'm getting this error in the console:

`message: "The variables input contains a field name 'owner' that is not defined for input object type 'XXXXXX' "`

If I filter by any other field like title, then the filters work, but I'm only getting this error with the **owner** field which is auto generated by Amplify.

### Expected behavior

To receive a kist of filtered items by owner.

### Reproduction steps

1. Create a new GraphQL model with owner auth rules.
2. Try to make a graphql call to the model filtering by the owner.
3. Receive an error stating that 'The variables input contains a field name 'owner' that is not defined for input object type'

### GraphQL schema(s)

<details>

```graphql
type TestModel
  @model(subscriptions: null)
  @auth(
    rules: [
      { allow: owner, operations: [read, create] }
      { allow: groups, groups: ["Admin"] }
    ]
  ) {
  id: ID!
  title: String!
}
```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by ykethan** [comment] 2022-06-10 17:06
Hello @jerocosio, Thank you for reaching out. The owner attribute is an auto filled attribute, AppSync automatically segregates access to the items depending on the owner attribute and user login. 
In order to filter the owner field I added the `owner: String` to the model. On testing the application i observed the following.

On a create mutation AppSync will autofill the owner
![image](https://user-images.githubusercontent.com/87995712/173115271-f5cdf654-ff4e-4a51-9c24-cc2bebf4e4f9.png)

but on performing a list query with the filter the operation does not return any data.
![image](https://user-images.githubusercontent.com/87995712/173115770-af288e61-f1e2-4c53-85e0-c4b476ae39d5.png)

If we fill the owner field manually, 
![image](https://user-images.githubusercontent.com/87995712/173115980-c8c1726b-a9d9-4879-8242-a3eff67f34c6.png)

the list operation will return the item created
![image](https://user-images.githubusercontent.com/87995712/173116127-6de35d83-43f6-4797-81c5-291e64d9229c.png)

The end dynamoDB list appears as following.
![image](https://user-images.githubusercontent.com/87995712/173116221-8b6c1c8a-b886-4ca3-88cd-b0c9aa8b4485.png)

This appears to be a regression in the behaviour, with that being said I will be marking this as a bug.

**Comment by ykethan** [comment] 2022-06-10 19:01
Hey @jerocosio, On reaching to the team I was able to find that in order to filter a user when in Admin state. We will need to filter the user using the Cognito sub ID. As the owner field in DynamoDB currently populates the column in a <subID>::username format.

For example:
```
query MyQuery {
  listTodos(filter: {or: {owner: {beginsWith: "a7d0a89a-ac6d-4bf4-9e03-1111111"}}}) {
    items {
      id
      owner
    }
  }
}
```
 Additionally we can populate the owner field using the username and then query the list with the owner `eq` filter.

**Comment by ykethan** [comment] 2022-06-27 20:03
closing the issue due to inactivity

**Closed by ykethan** 2022-06-27 20:03 UTC
Labels: api-graphql, pending-close-response-required
