### ISSUE TITLE
Query parent object with limit 7 or less return with zero results

### ISSUE THREAD

**Issue by elusivestudio** [aws-amplify/amplify-category-api#1710] opened 2023-07-14 11:43 UTC
### Describe the bug

I have a parent object (User) which owns sub objects like profile, settings and items. 

Querying parent object with limit 7 or less always breaks, same with if I run query from AppSync query console.
![Screenshot 2023-07-14 at 13 17 45](https://github.com/aws-amplify/amplify-swift/assets/1245115/be346c4d-0cca-491d-af0b-5b617dddbe34)
![Screenshot 2023-07-14 at 13 38 32](https://github.com/aws-amplify/amplify-swift/assets/1245115/70aaf952-41cf-47b8-a633-1ed51512d9d5)

It works when limit is set to 8 or more.
![Screenshot 2023-07-14 at 13 26 44](https://github.com/aws-amplify/amplify-swift/assets/1245115/b685f340-7a1e-4758-8396-0aed04dd69d7)

### Steps To Reproduce

```swift
Steps to reproduce the behavior:
1. Login with an user account
2. Query parent object for the logged in owner with limit 5
3. Call return with successful response with a zero list of objects.
```

### Expected behavior

It should return the successful response results.

### Amplify Framework Version

2.11.5

### Amplify Categories

API

### Dependency manager

Swift PM

### Swift version

5

### CLI version

12.1.1

### Xcode version

14.3.1

### Relevant log output

```shell
<details>
<summary>Log Messages</summary>


INSERT LOG MESSAGES HERE
```
</details>
```


### Is this a regression?

No

### Regression additional context

_No response_

### Platforms

iOS

### OS Version

iOS 16.4

### Device

iPhone 14 Pro max

### Specific to simulators

iPhone 14 Pro

### Additional context

_No response_

**Comment by alharris-at** [comment] 2023-07-26 22:56
@elusivestudio could you run `amplify diagnose --send-report` and provide us with the report id? This will help us reproduce the issue you're seeing. I suspect that what Michael described above is accurate, but would like to confirm your use-case before we close the issue.

**Comment by alharris-at** [comment] 2023-07-27 16:54
I've been unable to reproduce this issue locally. I strongly suspect this is related to some dynamic filtering being performed in the resolver (e.g. you have a scan with filter predicates applied in DDB, or a query with filters applied). You can confirm this is happening by setting logging level to verbose, then running a query with that logging enabled (there's a checkbox in the appsync console), and inspecting the generated dynamodb datasource request.

<img width="992" alt="Screenshot 2023-07-27 at 9 51 45 AM" src="https://github.com/aws-amplify/amplify-category-api/assets/91494052/1bad3a22-893c-4a0d-8025-cc3f3fa5c5f4">

For information on requesting subsequent pages of data, you can refer to the documentation here https://docs.amplify.aws/lib/graphqlapi/query-data/q/platform/ios/#list-subsequent-pages-of-items.

Closing out this issue, but if you find that you don't see a filter or predicate set on the query, feel free to reopen after running that `diagnose` command in my prior comment.

Cheers,
Al

**Closed by alharris-at** 2023-07-27 16:54 UTC
Labels: pending-triage, p2, api-graphql
