### ISSUE TITLE
Error: Cannot update GSI's properties other than Provisioned Throughput and Contributor Insights Specification. You can create a new GSI with a different name.

### ISSUE THREAD

**Issue by Taylor-S** [aws-amplify/amplify-category-api#774] opened 2022-08-18 02:23 UTC
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/dev/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v14.17.1

### Amplify CLI Version

9.2.1

### What operating system are you using?

Windows

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

- After receiving an email from Amazon around updating lambda functions runtime version to latest node version. I did that within console
    - I since then have tried changing it back to node 12
- I updated a function and attempted an amplify push which now errors with: "Cannot update GSI's properties other than Provisioned Throughput and Contributor Insights Specification. You can create a new GSI with a different name."
    - After googling I tried removing and re-adding the GSI on this table. I now have no GSI on this table and still get same error.
    - The table with issues in being used as a join table

### Amplify Categories

api

### Amplify Commands

push

### Describe the bug

Upon amplify push command, I keep running into the following error:  

![image](https://user-images.githubusercontent.com/17429999/185276833-af86652e-0a3a-456a-a6a2-523a4c23a854.png)

The table experiencing the issue I use as a join table.

### Expected behavior

I would like to be able to get the amplify push command as well as deployments working again. Any help is greatly appreciated!

### Reproduction steps

- Create an amplify project.
- Create a many to many relationship as seen here: https://docs.amplify.aws/cli/graphql/data-modeling/#belongs-to-relationship
- Manually update amplify lamdba functions to node 16 then back to 12.
    - I feel like this is most likely my issue...
- Run amplify push, it should break here from memory
- Manually remove the GSI on the join table.

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line
type Parent @model {
  id: ID!
  email: String!
  firstName: String!
  lastName: String!
  prefix: String
  avatarId: Int!
  themeColor: String!
  students: [Student] @manyToMany(relationName: "ParentsStudents")
}

type Student @model {
  id: ID!
  email: String
  studentName: String!
  studentCode: String! @index(name: "studentByCode", sortKeyFields: ["createdAt"], queryField: "studentByCode")
  avatarId: Int!
  themeColor: String!
  teacher: Teacher! @belongsTo
  parents: [Parent] @manyToMany(relationName: "ParentsStudents")
  currentGoal: Goal @hasOne
  createdAt: AWSDateTime!
}

```

</details>

### Project Identifier

Project Identifier: 567aa1a8e857d2b2a182bd41487f625c

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Additional information
I also noticed some drifting issues with this resource. I have since re-added the GSIs to try and revert the drifting. Unfortunately I can't figure out how to re-add "SSESepcification". Not certain if resolving this will help.
![image](https://user-images.githubusercontent.com/17429999/185295305-c8b740d4-17f4-4066-af47-c8c966083a1b.png)

I'm still learning AWS and amplify so please let me know if there are further details I can provide. Thanks

**Comment by ykethan** [comment] 2022-09-19 14:27
Hey @Taylor-S, following up on this. Please do let us know if you require any assistance.

**Comment by Taylor-S** [comment] 2022-09-20 00:01
Hello @ykethan ,
I did not create the GSI manually, these were automatically generated by the manytomany relationship in my graphql schema.

What I think has happened was the deployment timed out. I have since then increased my build time. But that seemed to cause the issues with the GSIs. For me, removing the manytomany relationships from my schema, deploying, recreating them and deploying fixed the issue.

What would be your recommendation around this if the build were to again timeout? Not sure if you are able to reproduce the issue on your end, maybe by stopping the backend building halfway through?

Thanks for responding and sorry for late reply

**Comment by ykethan** [comment] 2022-09-20 21:24
hey @Taylor-S, wanted to confirm couple of things.

> Manually remove the GSI on the join table

1. was this modification made on the console. 
2. Is the application currently utilizing temporary credentials?
3. To understand , does this timeout on the `amplify push` operation locally or the amplify backend build. if this is the console build, could you let us know what was the timeout increased to mitigate the issue.

**Comment by Taylor-S** [comment] 2022-09-20 22:15
Hi @ykethan,

Apologies, following the reproduction steps aren't going to help as after investigating further the issue appears to have been the build timeout. Should I update this for you?

1. Yes this was, but due to removing and re-adding the many to many relationship in my schema, this action was redundant. Amplify created the join table and the GSIs along with it.
Here's what my schema looks like: 
![image](https://user-images.githubusercontent.com/17429999/191369357-0c7a9b68-4db4-4735-becf-50cb5d8c35cf.png)

2. No, the application has its own credentials which are permanent.

3. Timeout occurred within the AWS amplify backend build. I updated the build time from 30 to 60 minutes.
![image](https://user-images.githubusercontent.com/17429999/191370038-a4d23e11-8105-4c3d-88ea-f43ebc3c5444.png)

So this is what happens,
- Build would timeout at the provision step:
![image](https://user-images.githubusercontent.com/17429999/191370581-f4f43185-ba00-4942-891d-7230f0b29ed0.png)
 - Subsequent builds would fail at the backend stage. From caching issue I believe?
![image](https://user-images.githubusercontent.com/17429999/191371150-428d1c92-b696-4a3e-94bc-19485ed2a6ba.png)
- I then would try a rollback which would bypass the cache (I think), but then met with a state error. I "fixed" this by removing a json state file from the S3 bucket. I got this info from another thread somewhere.
![image](https://user-images.githubusercontent.com/17429999/191371875-7256ad6e-a93a-4891-bae5-d5d1e16cf07d.png)
- Then locally, when I tried to amplify push, I was met with the GSI errors. I wanted my local push to work before deploying.
![image](https://user-images.githubusercontent.com/17429999/185276833-af86652e-0a3a-456a-a6a2-523a4c23a854.png)
- The fix, removing the many to many relationship from schema, amplify push, re-adding many to many relationship, amplify push.
- I then updated my build timeout to 60 minutes before deploying which was then successful.

It seems the timeout would leave the build in a certain "non-complete" state which then put everything out of sync. Is that right? Due to this, it was no longer recognising the GSIs on the join table. Is there a better way around this if this were to occur in the future? Removing and re-adding the relationship deletes and re-adds the join table and therefore there is data loss which I can't have in my prod environment.
 
Thanks for taking the time to try understand my issue. Hope that makes sense for you.

**Comment by ykethan** [comment] 2022-09-23 14:11
Hey @Taylor-S, thank you for the information and including the screenshots. The amplify team is tracking issues caused by deployment failures and looking into to provide a robust experience. Additionally, I observed the CLI version being used in 7.6.15 while the issue opened provides 9.2.1. Could you let us if you have observed any inconsistencies in build behaviour between the latest and 7.6.15 CLI version?

**Comment by Taylor-S** [comment] 2022-11-28 06:47
Hi @ykethan,
I didn't notice any inconsistencies between the two CLI versions. I actually had this issue occur again in CLI 9.2.1 and went ahead to open a new issue.
The cause appears to be that if a backend deployment build fails, the GSI's attached to a join table seem to have drifted. Please see: https://github.com/aws-amplify/amplify-category-api/issues/988

We could probably close this issue as I have opened a newer issue which I think is clearer. 

Thanks!

**Comment by ykethan** [comment] 2022-11-28 19:07
Thank you for following up on this. Closing this in favor of https://github.com/aws-amplify/amplify-category-api/issues/988

**Closed by ykethan** 2022-11-28 19:07 UTC
Labels: pending-triage, ops-deploy, ops-drift, platform, deployment
