### ISSUE TITLE
deploy fails. waiter timeout

### ISSUE THREAD

**Issue by blinkdaffer** [aws-amplify/amplify-category-api#2474] opened 2024-04-18 13:50 UTC
### Environment information

```plain text
System:
  OS: macOS 13.3.1
  CPU: (8) arm64 Apple M1 Pro
  Memory: 192.69 MB / 16.00 GB
  Shell: /bin/zsh
Binaries:
  Node: 20.10.0 - /usr/local/bin/node
  Yarn: 1.22.19 - /opt/homebrew/bin/yarn
  npm: 10.2.4 - /opt/homebrew/bin/npm
  pnpm: undefined - undefined
NPM Packages:
  @aws-amplify/backend: 0.13.0-beta.18
  @aws-amplify/backend-cli: 0.12.0-beta.20
  aws-amplify: 6.0.17
  aws-cdk: 2.133.0
  aws-cdk-lib: 2.133.0
  typescript: 5.3.3
AWS environment variables:
  AWS_SDK_LOAD_CONFIG = 1
  AWS_STS_REGIONAL_ENDPOINTS = regional
  AWS_NODEJS_CONNECTION_REUSE_ENABLED = 1
No CDK environment variables
```

### Description
When attempting to deploy a build, I encounter a failure related to a nested stack within AWS CloudFormation. The error message received is:

"Embedded stack arn:aws:cloudformation:us-east-1:7XXX was not successfully created: The following resource(s) failed to create: [amplifyDataCompanyNestedStackCompanyNestedStackResource1A74F86D]."

 
![image](https://github.com/aws-amplify/amplify-backend/assets/85892664/a65377b2-cf86-4a03-8698-59d86a273b99)

```   
 Iteration: a
      .model({
        companyId: a.id(),
        type: a.string(),

        company: a.belongsTo("Company", "companyId"),
      })
      .authorization([a.allow.multipleOwners()]),
  Company: a
      .model({
        companyName: a.string(),
        companyBackground: a.string(),
        iterations: a.hasMany("Iteration", "companyId"),
        members: a.string().array(),

      })
      .authorization([a.allow.multipleOwners().inField("members")]),
      
      ```

**Comment by blinkdaffer** [comment] 2024-04-19 14:53
any suggestions on this issue

**Comment by AnilMaktala** [comment] 2024-04-19 18:09
Hey @blinkdaffer, Thank you for raising this. This issue seems to be a duplicate of #2189 .

**Comment by AnilMaktala** [comment] 2024-06-13 19:25
We are closing this issue in favor of #2189. Please refer to that issue for future updates.

**Closed by AnilMaktala** 2024-06-13 19:25 UTC
Labels: bug, duplicate, transferred, Gen 2
