### ISSUE TITLE
[Gen2] - Feature Request to set indexName or fields on relationships

### ISSUE THREAD

**Issue by aroradev-dms** [aws-amplify/amplify-category-api#2315] opened 2024-03-03 09:36 UTC
### Describe the feature you'd like to request

In V1, we can set up a custom field to store the reference of the parent object. 

Link : https://docs.amplify.aws/javascript/build-a-backend/graphqlapi/data-modeling/#belongs-to-relationship

An example bidirectional `has many` relationship is shown below :-

```
type Post @model {
  id: ID!
  title: String!
  comments: [Comment] @hasMany(indexName: "byPost", fields: ["id"])
}
```
```
type Comment @model {
  id: ID!
  postID: ID! @index(name: "byPost", sortKeyFields: ["content"])
  content: String!
  post: Post @belongsTo(fields: ["postID"])
}
```

However, we cannot seem to achieve this in V2.

### Describe the solution you'd like

I would like to propose this FR to achieve this in V2.

### Describe alternatives you've considered

NA

### Is this something that you'd be interested in working on?

- [X] 👋 I may be able to implement this feature request

### Would this feature include a breaking change?

- [X] ⚠️ This feature might incur a breaking change

**Comment by AnilMaktala** [comment] 2024-03-04 13:54
Hey @aroradev-dms, Thank you for bringing this to our attention. It appears to be a duplicate of #2312. Please review #2312 and share your comments there. If you believe this is a different feature request, please inform us, and we will keep this ticket open for the team to conduct a more in-depth review and evaluation.

**Closed** 2024-03-04 13:55 UTC
Labels: duplicate, feature-request, pending-response, Gen 2
