### ISSUE TITLE
Resolvers are not being updated in AppSync (using Aurora)

### ISSUE THREAD

**Issue by zbsergio** [aws-amplify/amplify-category-api#178] opened 2021-07-09 10:17 UTC
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm install amplify

### Amplify CLI Version

5.1.0

### What operating system are you using?

Mac

### Amplify Categories

api

### Amplify Commands

push

### Describe the bug

The resolvers are not being updated to the appsync when they are changed manually in Amplify directory under resolvers, both for new queries and existing queries.

### Expected behavior

The resolvers all should be updated to the app sync

### Reproduction steps

1. I have created the db using amplify api add-graphql-datasource
2. I then create a new query (or update an existing one) under schema.graphql 
type Query {
  listPortfoliosByFirm(firm: String!): [portfolio]
}
3. I add the 2 files of req and res in the resolvers
4. I update the StacksCustomResolvers
5. I amplify push --yes

Result: the query is added the datasource but the resolver is not updated - instead it shows the "Pets" example

### GraphQL schema(s)

```gql
type Query {
  listPortfoliosByFirm(firm: String!): [portfolio]
}

input CreatePortfolioInput {
  firm: String!
  name: String!
  symbol: String!
  weight: Float
  customerID: Int
}

type portfolio {
  id: Int
  firm: String!
  name: String!
  symbol: String!
  weight: Float
  customerID: Int
}

input UpdatePortfolioInput {
  id: Int!
  firm: String
  name: String
  symbol: String
  weight: Float
  customerID: Int
}

type Mutation {
  deletePortfolio(id: Int!): portfolio
  createPortfolio(createPortfolioInput: CreatePortfolioInput!): portfolio
  updatePortfolio(updatePortfolioInput: UpdatePortfolioInput!): portfolio
}

type Subscription {
  onCreatePortfolio: portfolio @aws_subscribe(mutations: ["createPortfolio"])
}

schema {
  query: Query
  mutation: Mutation
  subscription: Subscription
}

```
### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by renebrandel** [comment] 2022-09-21 04:18
Hi - Thanks for raising this. Unfortunately, we don't have any immediate updates on the GraphQL Transformer v1 at this point. We are looking to address this via this RFC to better support relational data sources as an immediate priority with GraphQL Transformer v2. 

I would love to get your thoughts and feedback on that: https://github.com/aws-amplify/amplify-category-api/issues/815

**Comment by chrisbonifacio** [comment] 2024-02-07 21:39
Closing this issue as it seems to be addressed in the new feature support for Aurora/MySQL/PostgreSQL databases.

Please refer to our documentation on how to connect to an existing SQL/PostgreSQL database:
https://docs.amplify.aws/javascript/build-a-backend/graphqlapi/connect-api-to-existing-database/

I was unable to reproduce the issue by deploying the following schema first:

```graphql
type Todo @refersTo(name: "todos") @model @auth(rules: [{ allow: public }]) {
  id: String! @primaryKey
  description: String
}
```

then updating it to the following:

```graphql
type Todo
  @refersTo(name: "todos")
  @model(
    mutations: { create: "newTodo", delete: "deleteTodo", update: null }
    timestamps: null
    subscriptions: null
  )
  @auth(rules: [{ allow: public }]) {
  id: String! @primaryKey
  description: String
}
```

running the renamed mutation seems to work, the update mutation is not generated as expected, etc.

If anyone runs into any issues with the `AmplifyGraphqlApi` construct's support for SQL/PostgreSQL databases, please open a new issue.

**Closed by chrisbonifacio** 2024-02-07 21:39 UTC
Labels: feature-request, api-graphql, aurora
