### ISSUE TITLE
🛑 ENOENT: no such file or directory, open '.../schema.graphql'

### ISSUE THREAD

**Issue by LeoReubelt** [aws-amplify/amplify-category-api#1385] opened 2023-04-03 20:39 UTC
### Amplify CLI Version

11.0.3

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No.

### Describe the bug

When perform amplify push, it is successful.
When I push to my git repo, and it tries to deploy, I get the following...

```
🛑 ENOENT: no such file or directory, open '.../schema.graphql'
Resolution: Please report this issue at https://github.com/aws-amplify/amplify-cli/issues and include the project identifier from: 'amplify diagnose --send-report'
                                 Learn more at: https://docs.amplify.aws/cli/project/troubleshooting/
There was an error initializing your environment.
🛑 ENOENT: no such file or directory, stat '.../schema.graphql'
```

I see a previous issue that says 11.0.3 fixes this issue. 
In the console, under Amplify build settings, 'Amplify CLI' is set to 'Latest'.

### Expected behavior

I would expect it to build successfully.

### Reproduction steps

Idk. This is a very large project and has been building successfully until last week. 
All we did was upgrade the cli to the current version. Previous version was 9.2.1.
We have our schema files broken up into separate files and subdirectories in the amplify/backend/schema/ directory.

### Project Identifier

I ran amplify diagnose --send-report.
But I got...

```
✅ Report saved: .../report-1680551269367
⠦ Sending zip
✖ Sending zip
```

So apparently it failed to send. And I didn't get a project identifier.
I have the report. But I don't know what is and what is not sensitive information in that report. So I didn't include it.

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by josefaidt** [comment] 2023-04-03 23:58
Hey @LeoReubelt thanks for clarifying! I've transferred this over to our API repo for visibility, where I believe this is a duplicate of https://github.com/aws-amplify/amplify-category-api/issues/1074

**Comment by LeoReubelt** [comment] 2023-04-04 11:06
Thanks @josefaidt

**Comment by LeoReubelt** [comment] 2023-04-04 13:40
When we deploy manually from the console....
CLI version 9.2.1 works.
CLI version 10.5.2 and 11.0.3 fail.

**Comment by brauliolledo** [comment] 2023-04-04 15:29
When looking at the code for the Amplify CLI, [this line](https://github.com/aws-amplify/amplify-cli/blob/0dab648a9ae50cf58b39263d64862dd34d5fdfc7/packages/amplify-provider-awscloudformation/src/admin-modelgen.ts#L72) calls for the `schema.graphql` file in the `api/projectName` folder... which doesn't exist when dealing with split schema files. I'm fairly certain this is where the error happens, since it's on the last step of the amplify push.

The `adminModelgen` function's implementation changes from CLI version to version. On `9.x` it first checks whether the app is "Amplify Admin enabled", which I take to mean "Amplify Studio enabled" now. Said check doesn't happen on `11.x`.

Also, when trying to look at the GraphQL schema through Amplify Studio it just errors out saying it couldn't find the schema.
![image](https://user-images.githubusercontent.com/32247933/229841888-7368f8eb-f890-420c-a906-b12d6ec9a6ab.png)

My guess is that the `adminModelgen` function is not implemented to deal with split schema files correctly.

**Comment by LeoReubelt** [comment] 2023-04-04 17:36
If we consolidate the graphql files in to a single schema.graphql file at the subject path, it works. but we would really rather not do that.

**Comment by marcvberg** [comment] 2023-04-13 21:25
I found the root cause for this issue and have described it along with the fix for it, closing as a duplicate of the issue where I commented the description: https://github.com/aws-amplify/amplify-category-api/issues/1074

**Closed** 2023-04-13 21:25 UTC
Labels: bug, duplicate, api-graphql, transferred
