### ISSUE TITLE
ConnectionStack limit exceed - Template may not exceed 1000000 bytes in size

### ISSUE THREAD

**Issue by Santho24** [aws-amplify/amplify-category-api#2324] opened 2024-03-05 16:56 UTC
### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

20.10.0

### Amplify CLI Version

12.10.0

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No

### Describe the bug

This error is blocking us from making any further changes to our API. We have a large schema and sometimes when we try to push it gives us the error Template may not exceed 1000000 bytes in size and we noticed the "connection stack" file exceed the limit

Currently we are using --minify to reduce the size of "connection stack", but even this is not useful for longterm solution.

Even we tried the transform-conf.json to configure the custom stack but not luck, here we getting "Circular dependencies error"

### Expected behavior

We are expecting to increase this hard limit to more than 1Mb.

### Reproduction steps

1. Currently we reduce the belongsto
2. If we re-add all then we are getting this connection stack exceed 

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by AnilMaktala** [comment] 2024-03-05 17:29
Hey @Santho24, Thank you for reporting this issue. This appears to be a duplicate of #2153. Team is working on increasing the limits. Please subscribe to #2153 for future updates.

**Comment by Santho24** [comment] 2024-03-07 16:01
Thanks @AnilMaktala

**Closed** 2024-10-08 19:00 UTC
Labels: bug, duplicate
