### ISSUE TITLE
Update from elastic search to open search my query don'work

### ISSUE THREAD

**Issue by jcacu** [aws-amplify/amplify-category-api#1828] opened 2023-08-28 09:33 UTC
### How did you install the Amplify CLI?

npm

### Amplify CLI Version

12.1.0

### What operating system are you using?

windows 10

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

I have update from elastic search to open search

### Describe the bug

After update from elastic search to open search , all my query of appsync don't work , they retrive only old data from s3 and dynamo db.
opensearch version OpenSearch_2_7_R20230706

type FileManager {
    id: ID!
    key: String!
    category: String!
    subCategory: String!
    elab: Int!
    state: Int!
    consulenza: Boolean
    value: Float
    durata: Int
    rata: String
    npagine: String
    uploadedBy: String
    quietanza: String
    createdAt: AWSDateTime!
    updatedAt: AWSDateTime!
}

### Expected behavior

Query retrive all data

### Reproduction steps

 nothing

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by AnilMaktala** [comment] 2023-09-05 13:40
Hey @jcacu, Thank you for bringing this to our attention. This problem is a duplicate of issue #1297. Please consult the comments in #1297for a workaround and any upcoming developments.

**Closed by AnilMaktala** 2023-09-05 13:40 UTC
Labels: duplicate, pending-triage, api-graphql, @searchable
