### ISSUE TITLE
AWSTimestamp and complex sortKeys in secondary indexes cause 'Unknown type' errors

### ISSUE THREAD

**Issue by nima-nejad** [aws-amplify/amplify-category-api#2698] opened 2024-07-09 22:04 UTC
### Environment information

```plain text
System:
  OS: Linux 6.5 Ubuntu 22.04.4 LTS 22.04.4 LTS (Jammy Jellyfish)
  CPU: (8) x64 Intel(R) Core(TM) i7-7700T CPU @ 2.90GHz
  Memory: 16.49 GB / 31.20 GB
  Shell: /bin/bash
Binaries:
  Node: 20.15.0 - ~/.nvm/versions/node/v20.15.0/bin/node
  Yarn: undefined - undefined
  npm: 10.7.0 - ~/.nvm/versions/node/v20.15.0/bin/npm
  pnpm: undefined - undefined
NPM Packages:
  @aws-amplify/backend: 1.0.4
  @aws-amplify/backend-cli: 1.1.0
  aws-amplify: 6.4.0
  aws-cdk: 2.140.0
  aws-cdk-lib: 2.140.0
  typescript: 5.5.2
AWS environment variables:
  AWS_STS_REGIONAL_ENDPOINTS = regional
  AWS_NODEJS_CONNECTION_REUSE_ENABLED = 1
  AWS_SDK_LOAD_CONFIG = 1
No CDK environment variables
```

### Data packages

```plain text
├─┬ @aws-amplify/backend-cli@1.1.0
│ └─┬ @aws-amplify/schema-generator@1.2.0
│   └── @aws-amplify/graphql-schema-generator@0.9.2
└─┬ @aws-amplify/backend@1.0.4
  └─┬ @aws-amplify/backend-data@1.1.0
    └── @aws-amplify/data-construct@1.9.1
```

### Description

I'm encountering issues with Amplify Gen2 when using AWSTimestamp and complex sortKeys in secondary indexes. These problems persist even after upgrading Amplify packages as suggested in [previous issues.](https://github.com/aws-amplify/amplify-category-api/issues/2414#issuecomment-2112640272)

My model definition:
`Record: a
  .model({
    lotNumber: a.string(),
    lotId: a.string(),
    lot: a.belongsTo('ProductionLot', ['lotId','lotNumber']),
    timestamp: a.timestamp().required(),
    comment: a.string()
  })
  .secondaryIndexes((index) => [
    index('lotId').sortKeys(['timestamp']),
  ])
`
When trying to query using this index, I receive the following error:
`message: "Validation error of type UnknownType: Unknown type ModelAWSTimestampKeyConditionInput"
`

Additionally, when I tried to use multiple sortKeys like [rowType, 'timestamp'], it also threw an unknown type error.
Upon investigation, I found that in .amplify/artifacts/cdk.out, the generated query is:

`listRecordByLotIdAndTimestamp(
  lotId: String!,
  timestamp: ModelIntKeyConditionInput,
  sortDirection: ModelSortDirection,
  filter: ModelRecordFilterInput,
  limit: Int,
  nextToken: String
): ModelRecordConnection @aws_iam @aws_cognito_user_pools
`
It appears that the timestamp is being treated as ModelIntKeyConditionInput instead of an AWSTimestamp type. This mismatch seems to be causing the error.

**Steps to reproduce:**
Define a model with AWSTimestamp in a secondary index
Attempt to query using this index
Observe the "Unknown type ModelAWSTimestampKeyConditionInput" error

**Expected behavior:**
The query should accept AWSTimestamp input for the timestamp field and execute successfully.
Complex sortKeys (e.g., [rowType, 'timestamp']) should be supported in secondary indexes.

**Actual behavior:**
The query fails with an unknown type error for ModelAWSTimestampKeyConditionInput.
Using complex sortKeys also results in unknown type errors.

The documentation on defining sortKeys is quite brief. It would be helpful to have more detailed explanations and examples of how to properly define and use complex sortKeys in secondary indexes.
**Request:** Could you please provide guidance on how we can actually define sortKeys, especially when using multiple fields or AWSTimestamp? The current documentation lacks detailed examples for these scenarios.

**Comment by chrisbonifacio** [comment] 2024-07-11 16:13
Hi @nima-nejad thanks for raising this issue. I wasn't able to reproduce the exact error message mentioned in the description but I did run into another type issue:

![CleanShot 2024-07-11 at 12 12 09@2x](https://github.com/aws-amplify/amplify-category-api/assets/16952986/b7cf8177-a422-40a0-9596-7c756c1ef9e4)

can you try running the following command?

```sh
npm update @aws-amplify/data-schema
```

Also, please try restarting your TS server afterwards, restarting VSCode, even re-installing dependencies if those don't help.

**Comment by grahamjamesr7** [comment] 2024-07-13 16:05
Hi, I think this issue is affecting me as well. I'm connecting to an existing PostgreSQL database.

I initially had the above issue as noted, but running 
```bash

npm update @aws-amplify/data-schema
```

Corrected the type issue noted above. However the secondary issues remain. 

Here's my model:
```ts
export const schema = configure({
  database: {
    identifier: "IDltDipO8fUAZbkjpniyjNw",
    engine: "postgresql",
    connectionUri: secret("SQL_CONNECTION_STRING"),
  },
}).schema({
reportsSummary1m: a
      .model({
        locationid: a.id().required(),
        bucket: a.datetime().required(),
        avgtime: a.float(),
      })
      .identifier(["locationid", "bucket"]),
});
```

And doing a basic list operation:
```ts

const data = await client.models.reportsSummary1m.list({
      limit: 10,
    });
    
```
Results in the following error:

```json
{
    "data": null,
    "errors": [
        {
            "path": null,
            "locations": [
                {
                    "line": 5,
                    "column": 5,
                    "sourceName": null
                }
            ],
            "message": "Validation error of type UnknownArgument: Unknown field argument bucket @ 'listReportsSummary1ms'"
        }
    ]
}
```

**Comment by chrisbonifacio** [comment] 2024-07-15 17:48
Hi @nima-nejad @grahamjamesr7, this seems like it could be a duplicate of another issue that was opened recently:

https://github.com/aws-amplify/amplify-category-api/issues/2701

**Comment by chrisbonifacio** [comment] 2024-07-16 13:38
Hi @nima-nejad , we just released a fix for this issue in `@aws-amplify/data-schema` v1.3.5. Please upgrade your amplify backend and data-schema packages to the latest versions.

```sh
npm install @aws-amplify/backend@latest @aws-amplify/backend-cli@latest
```

```sh
npm update @aws-amplify/data-schema
```

**Closed by chrisbonifacio** 2024-07-16 13:38 UTC
Labels: bug, data-schema

**Comment by chrisbonifacio** [comment] 2024-07-16 14:18
Hi @riacoding, 

> Record: a .model({ lotNumber: a.string(), lotId: a.string(), lot: a.belongsTo('ProductionLot', ['lotId','lotNumber']), timestamp: a.timestamp().required(), comment: a.string() }) .secondaryIndexes((index) => [ index('lotId').sortKeys(['timestamp']), ])

@grahamjamesr7 I think the issue you're running into is different from the one described here and https://github.com/aws-amplify/amplify-category-api/issues/2701. Can you open a new issue with reproduction steps or a link to a sample repo that reproduces the issue?

I tried to reproduce with the schema you shared but could not:

![CleanShot 2024-07-16 at 10 17 37@2x](https://github.com/user-attachments/assets/c7cb7869-705e-44b0-ba7b-4181cd44f96e)
