### ISSUE TITLE
Deployment failure in CFN: `The following resource(s) failed to create: [amplifyDataProfileNestedStackProfileNestedStackResourceB5430B89]`

### ISSUE THREAD

**Issue by johnpc** [aws-amplify/amplify-category-api#2271] opened 2024-02-14 16:40 UTC
### Amplify CLI Version

0.11.1

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made

### Describe the bug

I have an app whose schema is unable to deploy to CFN, the deployment rolls back without a useful error message.

### Expected behavior

The deployment should succeed.

### Reproduction steps

Clone the repo and install dependencies:

```bash
git clone https://github.com/johnpc/amplify-demo-data-type-infinite
cd amplify-demo-data-type-infinite
npm install
```

Run the sandbox deployment:

```bash
npx amplify sandbox
```

Intermittently (and strangely, it may depend on the AWS account) the deployment will fail when starting from zero (all resources destroyed).

The error in the Cloudformation console shows:

```bash
Embedded stack arn:aws:cloudformation:us-west-2:566092841021:stack/amplify-dfmueaydqaxlo-pr14-branch-a7281b577b-data7552DF31-1JSVQR8U424A8/f4783232-cac5-11ee-8186-0aa259bf7d4b was not successfully created: The following resource(s) failed to create: [amplifyDataProfileNestedStackProfileNestedStackResourceB5430B89].
```

The issue seems most likely to occur on a freshly created AWS accounts, although I've been seeing it on older AWS accounts as well.

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by AnilMaktala** [comment] 2024-02-14 19:10
Hey @johnpc, When I follow the steps outlined in the issue description, I am unable to reproduce the problem in my account. To better troubleshoot, should I try deleting the resources and re-running `npx amplify sandbox` clean to see if I can replicate the issue that way? Please let me know if there are any other specific steps I should try to reproduce the bug
<img width="899" alt="image" src="https://github.com/aws-amplify/amplify-category-api/assets/3206171/c9bb25e0-d9c4-4afe-8f5d-b3ba0e3828d0">

**Comment by johnpc** [comment] 2024-02-14 22:17
It seems like it can be reproduced most reliably in new AWS accounts.

**Comment by AnilMaktala** [comment] 2024-02-22 19:20
@johnpc, can you please confirm is the table resource failing or any other resource is failed to create in failing stack?

**Comment by phani-srikar** [comment] 2024-02-23 20:04
You can check the resource that's failing by looking at the `resources` tab when the nested stack is being deployed and you should be able to find the `<modelName>Table` custom resource and confirm if this is stuck in `update_in_progress`.

**Comment by gcoxdev** [comment] 2024-02-27 01:31
I'm getting a similar issue. I think it's related to the model size. If I reduce the number of models then add them one at a time it will work but all at once is a no go. Here's a similar issue that was closed but I think the issue persists https://github.com/aws-amplify/amplify-category-api/issues/2189

**Comment by jFensch** [comment] 2024-03-15 13:38
I'm experiencing the same issue.  Reducing the number of models and adding incrementally seems to work around the issue, but this is not a long term solution.

**Comment by manuelbachl** [comment] 2024-04-14 10:31
> I'm experiencing the same issue. Reducing the number of models and adding incrementally seems to work around the issue, but this is not a long term solution.

Worked for me too. As you already said, not satisfying but working ;)

**Comment by AnilMaktala** [comment] 2024-06-13 19:27
We are closing this issue in favor of https://github.com/aws-amplify/amplify-category-api/issues/2189. Please refer to that issue for future updates.

**Closed by AnilMaktala** 2024-06-13 19:27 UTC
Labels: bug, duplicate, Gen 2
