### ISSUE TITLE
Function access to API not applied

### ISSUE THREAD

**Issue by johnf** [aws-amplify/amplify-category-api#679] opened 2022-05-19 23:52 UTC
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

yarn

### If applicable, what version of Node.js are you using?

v16.15.0

### Amplify CLI Version

8.2.0

### What operating system are you using?

Ubuntu

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No

### Amplify Categories

function, api

### Amplify Commands

add, push

### Describe the bug

* Add a GraphQL API with IAM auth
* amplify push
* Add a lambda function
* amplify push
* Give the lambda function permissions to the API

The VTL is updated locally but not remotely to give the function access.

You can see this during the pus in that there is "No Change" to the API
Modifying the schema and then pushing fixes it.

See below for detailed steps to reproduce and you can follow along at

See below for detailed steps to reproduce and you can follow along at
https://github.com/johnf/amplify-api-lambda-perms-bug

To me it looks like the permission change on the function isn't triggering that the API also needs to be updated.

### Expected behavior

Permissions are correctly applied to appsync

### Reproduction steps

See https://github.com/johnf/amplify-api-lambda-perms-bug#readme

### GraphQL schema(s)

<details>
https://github.com/johnf/amplify-api-lambda-perms-bug/blob/main/amplify/backend/api/amplifyapivtl/schema.graphql
</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by KevinSnyderCodes** [comment] 2022-10-10 23:51
Alternatively, you can run:

```sh
amplify push --force api
```

Which will rebuild and push the VTL resolvers, without having to make any changes (e.g. blank space) to the schema to trigger a change.

**Comment by alex-griffiths** [comment] 2022-12-08 00:45
I'll add to this to keep some record of the trouble shooting I've been doing. Changing the schema as suggested @ykethan was one solution. Another problem I have found that is related to the VTL resolvers not getting updated properly was caused by the mock api resolvers preventing changes to the API schema from updating the deployed resolvers. Deleting these allowed the remote VTL resolvers to update and allowed my lambda to perform queries/mutations.

**Comment by josefaidt** [comment] 2023-04-18 17:04
related https://github.com/aws-amplify/amplify-category-api/issues/100

**Comment by jeff-accountably** [comment] 2023-04-26 21:29
This is such an annoying bug, when developing I keep forgetting about it. Making minor changes to the schema just force the resolvers to update is not a good work around.

**Comment by jeff-accountably** [comment] 2023-04-26 21:35
> Alternatively, you can run:
> 
> ```shell
> amplify push --force api
> ```
> 
> Which will rebuild and push the VTL resolvers, without having to make any changes (e.g. blank space) to the schema to trigger a change.

This does not fix the issue for me.

**Comment by defish1962** [comment] 2023-05-26 18:26
Perhaps this issue should be called out in the Amplify documents since it has been open for over a year without resolution. I just spent several hours pulling my hair out trying to make IAM authorization work with my previously created Lambda functions and having no idea why it wasn't working. After adding a comment to the schema.graphql file and doing an amplify push the problem they immediately started working.

**Comment by ethan021021** [comment] 2023-07-13 23:53
Any updates on fixing this? Just had to do the same empty line trick to our schema.graphql and everything started working as expected.. Definitely an odd workaround.

**Comment by metuuu** [comment] 2023-09-06 07:54
I had this issue also. It was really frustrating to find out it was just another amplify bug...

**Comment by qwikag** [comment] 2023-09-20 16:12
here is my experience.
I was getting this body.error.message, adding to this thread (if not relevant I can remove!):

> body:  {
>   data: { listLogins: null },
>   errors: [
>     {
>       path: [Array],
>       data: null,
>       errorType: 'Unauthorized',
>       errorInfo: null,
>       locations: [Array],
>       message: 'Not Authorized to access listLogins on type Query'
>     }
>   ]
> }

**The process I took.**
I stood up a whole new App from amplify init.
Installing backend (except my problematic function): API(Cognito, IAM), Auth(userpools, groups), adding only the PostConfirmTrigger (Add-to-Group function)
Then setup my GraphQL tables, Added : @auth(rules: [{allow: private, provider: iam},...
I ran > amplify api gql-compile and > amplify codegen
I ran > amplify push --force api
Added my custom PostAuth trigger (custom function)
Updated my custom PostAuth trigger (with api access)
added the SDK v3, used the node-fetch library, and pretty much duplicated the guide code: [https://docs.amplify.aws/guides/functions/graphql-from-lambda/q/platform/js/#iam-authorization](https://docs.amplify.aws/guides/functions/graphql-from-lambda/q/platform/js/#iam-authorization)

The guide code was pretty good, but it still gave me the same error.
After a complete re-build from blank app and following all guides step by step to still have the same error was super frustrating.

**Last ditch effort:** I needed to remove a table from the schema.graphql
ran >amplify push --force api
made sure it processed the mutations and queries again

**And it worked! But I do not know what was the piece that worked. Nor what is going to happen when I add my next @Auth IAM table.**

**Comment by kylekirkby** [comment] 2023-11-12 13:39
What's the recommended fix for this? Everything was working fine and now its not etc...

```vtl
## [Start] Field Authorization Steps. **
#set( $isAuthorized = false )
#if( $util.authType() == "IAM Authorization" )
  #foreach( $adminRole in $ctx.stash.adminRoles )
    #if( $ctx.identity.userArn.contains($adminRole) && $ctx.identity.userArn != $ctx.stash.authRole && $ctx.identity.userArn != $ctx.stash.unauthRole )
      #return($context.source.sendEmail)
    #end
  #end
  #if( !$isAuthorized )
    #if( ($ctx.identity.userArn == $ctx.stash.authRole) || ($ctx.identity.cognitoIdentityPoolId == $ctx.stash.identityPoolId && $ctx.identity.cognitoIdentityAuthType == "authenticated") )
      #set( $isAuthorized = true )
    #end
  #end
#end
#if( $util.authType() == "User Pool Authorization" )
  #set( $isAuthorized = true )
#end
#if( !$isAuthorized )
$util.unauthorized()
#end
$util.toJson({"version":"2018-05-29","payload":{}})
## [End] Field Authorization Steps. **
```

This is what my `Mutation.sendEmail.auth.req.vtl` mutation resolve looks like in the broken state. Do I need to add a `custom-roles.json` file and add these lambda roles manually?

**Comment by kylekirkby** [comment] 2023-11-12 15:24
It looks like the `FunctionDirectiveStack.json` file is not updating the context stash as with the generated resolvers. What's weird is that I'm sure this has been working. Not matter what I do, I cannot get the custom mutation resolvers to respect the IAM role auth rules...

E.g custom mutation with @auth rules

```gql
type Mutation {
	editConnectedAccount(input: EditConnectedAccountInput!): ConnectedAccount
		@function(name: "manageConnectedAccounts-${env}")
		@auth(rules: [{ allow: private }, { allow: private, provider: iam }])

```

I'm on the latest version of the amplify cli. This looks like a massive oversight to me.

**Comment by defish1962** [comment] 2023-11-12 15:46
> It looks like the `FunctionDirectiveStack.json` file is not updating the context stash as with the generated resolvers. What's weird is that I'm sure this has been working. Not matter what I do, I cannot get the custom mutation resolvers to respect the IAM role auth rules...
> 
> E.g custom mutation with @auth rules
> 
> ```graphql
> type Mutation {
> 	editConnectedAccount(input: EditConnectedAccountInput!): ConnectedAccount
> 		@function(name: "manageConnectedAccounts-${env}")
> 		@auth(rules: [{ allow: private }, { allow: private, provider: iam }])
> ```
> 
> I'm on the latest version of the amplify cli. This looks like a massive oversight to me.

Did you modify the schema.graphql file and do an amplify push? Just add a comment or modify a comment, save and then push. That action seems to update the IAM permissions, whether set in a custom-roles.json file or added through amplify add/update function.

**Comment by kylekirkby** [comment] 2023-11-12 15:55
So I've rolled back to `12.3.0` and the inline adminRoles are successfully being written to the auth resolvers... 

@josefaidt - Hey! Can you take a look at this bug since this has broken in the latest release. Custom queries / mutations are not correctly having their RequestMappingTemplates updated in the FunctionDirectiveStack.json files. The adminRoles used to be inlined and have since been moved to VTL mapping.

**Comment by kylekirkby** [comment] 2023-11-12 15:56
Also, adding a test to make sure all VTL resolvers have the correct adminRoles added would be great to prevent this happening going forward.

**Comment by kylekirkby** [comment] 2023-11-14 07:47
> > It looks like the `FunctionDirectiveStack.json` file is not updating the context stash as with the generated resolvers. What's weird is that I'm sure this has been working. Not matter what I do, I cannot get the custom mutation resolvers to respect the IAM role auth rules...
> > E.g custom mutation with @auth rules
> > ```graphql
> > type Mutation {
> > 	editConnectedAccount(input: EditConnectedAccountInput!): ConnectedAccount
> > 		@function(name: "manageConnectedAccounts-${env}")
> > 		@auth(rules: [{ allow: private }, { allow: private, provider: iam }])
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I'm on the latest version of the amplify cli. This looks like a massive oversight to me.
> 
> Did you modify the schema.graphql file and do an amplify push? Just add a comment or modify a comment, save and then push. That action seems to update the IAM permissions, whether set in a custom-roles.json file or added through amplify add/update function.

Yes I had done that multiple times with and without the force flag.  This is a bug since moving the adminRoles out of the VTL resolvers source code.

**Comment by rafaelfaria** [comment] 2023-11-22 11:33
+1 for having this working and now i keep getting `Not Authorized to access MY_GRAPHQL_CUSTOM_FUNCTION on type Mutation`

**Comment by johndebord** [comment] 2023-11-24 05:39
Is there a amplify CLI command that just re-pushes/rebuilds everything? I'd rather do that than deal with blank lines

**Comment by Etep15** [comment] 2023-12-02 00:23
`amplify push --force api` I believe will do that @johndebord

**Comment by johndebord** [comment] 2023-12-15 08:47
Would be nice to have this fixed.

**Comment by johndebord** [comment] 2023-12-15 22:44
I encounter this issue approximately once a week.

In the latest occurrence, I implemented a flow where I create a user in a Cognito Pool, and subsequently, albeit not immediately, create a user in another database. After a period, when I perform a comparison between the Cognito Pool user and the database user, it fails. The error isn't immediately apparent, leading me to investigate various potential causes. However, the root cause turned out to be this particular issue, which I find myself running into frequently.

**Comment by johndebord** [comment] 2024-02-14 06:26
Any progress or clarification on this? It'd be valuable to have something documented here about the ins-and-outs of this situation by an experienced team member.

**Closed** 2024-02-21 22:27 UTC
Labels: bug, p2, graphql-transformer-v2, functions

**Comment by joekiller** [comment] 2024-02-22 02:05
For those curious this is the codepath triggered via the force:

https://github.com/aws-amplify/amplify-category-api/blob/30a297217e2cad518d42c23665d2208431845f14/packages/amplify-category-api/src/force-updates/force-refresh-schema.ts#L10
