### ISSUE TITLE
The query set in secondaryIndexes cannot be executed.

### ISSUE THREAD

**Issue by rnrnstar2** [aws-amplify/amplify-category-api#2477] opened 2024-04-19 10:39 UTC
### Environment information

```plain text
npx amplify info                                                                                                          【 main 】
System:
  OS: macOS 14.0
  CPU: (10) arm64 Apple M2 Pro
  Memory: 220.56 MB / 16.00 GB
  Shell: /bin/zsh
Binaries:
  Node: 20.5.0 - /usr/local/bin/node
  Yarn: 1.22.19 - /usr/local/bin/yarn
  npm: 9.8.0 - /usr/local/bin/npm
  pnpm: 8.15.5 - ~/Library/pnpm/pnpm
NPM Packages:
  @aws-amplify/backend: 0.13.0-beta.20
  @aws-amplify/backend-cli: 0.12.0-beta.22
  aws-amplify: 6.0.28
  aws-cdk: 2.138.0
  aws-cdk-lib: 2.138.0
  typescript: 5.4.5
AWS environment variables:
  AWS_PROFILE = cloudteam
  AWS_DEFAULT_PROFILE = cloudteam
  AWS_STS_REGIONAL_ENDPOINTS = regional
  AWS_NODEJS_CONNECTION_REUSE_ENABLED = 1
  AWS_SDK_LOAD_CONFIG = 1
No CDK environment variables
```

### Description

The query set in secondaryIndexes cannot be executed.

````
OnePieceItem: a
 .model({
   name: a.string().required(),
   getInfo: a.string(),
 })
 .secondaryIndexes((index) => [
   index("getInfo").sortKeys(["name"]).queryField("listByGetInfo"),
 ])
 .authorization([
   a.allow.owner(),
   a.allow.private().to(["read", "update", "create"]),
 ]),

const res = await client.models.OnePieceItem.listByGetInfo({
   getInfo,
 });
````

Property 'listByGetInfo' has type '{ create: (model: { [x: string]: { [x: number]: string; toString: () => string; charAt: (pos: number) => string; charCodeAt: (index: number) => number; concat: (...args: (string | ConcatArray<string>)[]) => string[]; ... 71 more ...; readonly [Symbol.unscopables]: { ...; }; }; }, options?: { ...; }) => Does not exist in SingularRetur...'.

**Comment by AnilMaktala** [comment] 2024-04-19 18:38
Hey @rnrnstar2, Thank you for raising this. We have a follow up question, Have you deployed your backend resources? Can you verify in AppSync console and confirm `listByGetInfo` query exist?

**Comment by rnrnstar2** [comment] 2024-04-22 03:11
Yes, appsync has `listByGetInfo`.

![スクリーンショット 2024-04-22 12 10 43](https://github.com/aws-amplify/amplify-category-api/assets/39724729/c3542df0-b10a-48da-b298-8691da616568)

**Comment by rnrnstar2** [comment] 2024-04-30 04:00
I selected multiple sortKeys for secondaryIndexes.
Then I couldn't get the list.

```
Post: a
      .model({
        name: a.string().required(),
        categoryId: a.id().required(),
        s3ImgKey: a.string(),
        message: a.string().required(),
        gender: a.string().required(),
        prefecture: a.string().required(),
        ageGroup: a.string().required(),
        category: a.belongsTo("Category", "categoryId"),
      })
      .secondaryIndexes((index) => [
        index("categoryId")
          .sortKeys(["gender", "prefecture", "ageGroup"])
          .queryField("listByCategoryId"),
      ]),
```

```
// @ts-ignore
      const { data: posts, errors } = await client.models.Post.listByCategoryId(
        {
          categoryId,
          gender: {
            eq: gender,
          },
          prefecture: {
            eq: prefecture,
          },
        }
      );
```

```
indexQuery.mjs:76 Uncaught (in promise) TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
```

**Comment by chrisbonifacio** [comment] 2024-05-07 18:25
Hi @rnrnstar2 thanks for raising this issue.

This seems to be a duplicate of another issue that was opened regarding composite identifiers.

Please track this issue for updates: https://github.com/aws-amplify/amplify-category-api/issues/2526

**Comment by iartemiev** [comment] 2024-05-14 11:41
We've patched this bug in the latest release of `@aws-amplify/data-schema`.
Please make sure you're using at least `@aws-amplify/backend@1.0` and then run `npm update @aws-amplify/data-schema` to consume the patch.

**Closed by iartemiev** 2024-05-14 11:41 UTC
Labels: bug, duplicate, pending-response, transferred, data-schema
