### ISSUE TITLE
Amplify CLI allows non alphanumeric container resource name and then fails on amplify push

### ISSUE THREAD

**Issue by Kaiki-kk** [aws-amplify/amplify-category-api#1489] opened 2023-05-21 07:32 UTC
### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

18.15.0

### Amplify CLI Version

12.0.0

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made

### Describe the bug

If a resource name other than alphanumeric letters is specified for the question `Please enter a friendly name for the resource that will be used as the label for this category in the project:`, the error message from the validation check is not displayed, and the error occurs when amplify is pushed. the error message is returned when amplify push is performed.

### Expected behavior

If a resource name other than alphanumeric with no uppercase letters is specified, the following error is displayed.
`Resource name should be alphanumeric with no uppercase letters`

### Reproduction steps

1. amplify add api
? Select from one of the below mentioned services: REST
? Which service would you like to use API Gateway + AWS Fargate (Container-based)
? Provide a friendly name for your resource to be used as a label for this category in the project: tes
t-container
? What image would you like to use ExpressJS - REST template
? When do you want to build & deploy the Fargate task On every "amplify push" (Fully managed container 
source)
? Do you want to restrict API access Yes

2. amplify push
3. amplify push fails with the following error returned `Template format error: Resource name apitest-container is non alphanumeric.`

![スクリーンショット 2023-05-21 18 33 53](https://github.com/aws-amplify/amplify-category-api/assets/75874736/6d757bf5-cc51-4d56-8b00-2e530a49ee01)

### Project Identifier

Project Identifier: 2bac005af622f370057a752387fa87b4

### Log output

<details>

```
🛑 Template format error: Resource name apitest-container is non alphanumeric.

```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by AnilMaktala** [comment] 2023-05-22 13:49
Hey @Kaiki-kk, Thank you for raising this issue. We have successfully reproduced the problem by following the steps outlined in the description. As a result, we are classifying this as a bug for the team to investigate further.
Steps:
1. `amplify init`
2. `amplify configure project` > Enable container-based deployments
3. `amplify add api`
      -  Select from one of the below mentioned services: REST
      - Which service would you like to use API Gateway + AWS Fargate (Container-based)
      - Provide a friendly name for your resource to be used as a label for this category in the project: test-container
      - What image would you like to use ExpressJS - REST template
      - When do you want to build & deploy the Fargate task On every "amplify push" (Fully managed containersource)
      - Do you want to restrict API access No

4. `amplify push`



<img width="593" alt="image" src="https://github.com/aws-amplify/amplify-category-api/assets/3206171/fd6872ef-9b01-4647-badb-839aded9e86d">

Note: Please be aware that the root cause appears to be the presence of the special character ('-') in the resource name. However, we were able to proceed successfully by updating the resource friendly name to 'testcontainer'.

**Comment by AnilMaktala** [comment] 2023-06-23 15:39
Hi @Kaiki-kk, Thank you for submitting the Pull Request for this issue. We have reviewed and merged your PR, and the changes have been released.

**Closed by AnilMaktala** 2023-06-23 15:39 UTC
Labels: bug, p3, containers
