### ISSUE TITLE
【gen2】Please support querying secondary indices with reqResBasedClient

### ISSUE THREAD

**Issue by sevenkkk** [aws-amplify/amplify-category-api#2626] opened 2024-06-14 11:57 UTC
### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

18

### Amplify CLI Version

 @aws-amplify/backend: 1.0.3   @aws-amplify/backend-cli: 1.0.1

### What operating system are you using?

mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

no

### Describe the bug

I'm implementing ISR (Incremental Static Regeneration) functionality with gen2 and Next.js 14. I've attempted to achieve this using the following approach, which works for fetching data by ID:

```javascript
import React from 'react';  
import { reqResBasedClient, runWithAmplifyServerContext } from "@/app/isr/[id]/_lib/amplifyServerUtils";  
import { unstable_cache } from "next/cache";  
  
const getCacheData = unstable_cache((id: string) => {  
    return runWithAmplifyServerContext({  
        nextServerContext: null,  
        operation: async (contextSpec) => {  
          const res = await reqResBasedClient.models.Todo.get(contextSpec, { id });  
          return res.data;  
        },  
    }),  
    ['todo'],  
    { revalidate: 30, tags: ['todo-list'] }  
});  
  
type PageProps = {  
    params: { id: string };  
};  
  
const Page = async ({ params }: PageProps) => {  
    const data = await getCacheData(params.id);  
    return (  
        <div>  
            content: {data?.content}  
        </div>  
    );  
};  
  
export default Page;
```

Since unstable_cache doesn't support cookies, I'm using reqResBasedClient to handle the server-side operations.

However, this approach doesn't work for secondary indexes. I would like to achieve something similar to fetching data by a secondary index, like this:

```javascript
const getCacheData = unstable_cache((type: string) => {  
    return runWithAmplifyServerContext({  
        nextServerContext: null,  
        operation: async (contextSpec) => {  
            const res = await reqResBasedClient.models.Todo.listByType(contextSpec, { type: 'TODO' });  
            return res.data;  
        },  
    }),  
    ['todo'],  
    { revalidate: 30, tags: ['todo-list'] }  
});
```

### Expected behavior

Secondary index support with contextSpec

### Reproduction steps

https://github.com/sevenkkk/amplify-next-isr/blob/main/app/isr/%5Bid%5D/page.tsx

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by chrisbonifacio** [comment] 2024-07-01 15:18
Hi @sevenkkk 👋 thanks for raising this issue. Can you explain a little bit more about why "this approach doesn't work for secondary indexes"?

Are you seeing any error messages or getting unexpected results?

**Comment by chrisbonifacio** [comment] 2024-07-01 17:46
Revisited this and realized that the issue is actually that the `listByType` query doesn't accept a contextSpec so I tried that got the error:

![CleanShot 2024-07-01 at 13 44 44@2x](https://github.com/aws-amplify/amplify-category-api/assets/16952986/2e10adee-8898-4f36-907f-5001347e35f9)

I'll mark this as a bug for the team to investigate further

**Comment by sevenkkk** [comment] 2024-07-02 02:14
@chrisbonifacio I hope you can help me deal with this problem first. Please

**Comment by chrisbonifacio** [comment] 2024-07-02 03:02
In the meantime, I would recommend using the `client.graphql` API instead to perform the query

**Comment by chrisbonifacio** [comment] 2024-07-02 03:11
Here's an example of what a refactor would look like:

```ts
import React from "react";
import {
  reqResBasedClient,
  runWithAmplifyServerContext,
} from "@/app/isr/[id]/_lib/amplifyServerUtils";
import { unstable_cache } from "next/cache";
import { listByType } from "@/queries";

const getCacheData = unstable_cache(
  (type: string) => {
    return runWithAmplifyServerContext({
      nextServerContext: null,
      operation: async (contextSpec) => {
        const res = await reqResBasedClient.graphql(contextSpec, {
          query: listByType,
          variables: {
            type,
          },
        });
        return res.data;
      },
    });
  },
  ["todo"],
  { revalidate: 30, tags: ["todo-list"] }
);

type PageProps = {
  params: { type: string };
};

const Page = async ({ params }: PageProps) => {
  const { listByType: data } = await getCacheData(params.type);
  return <div>content:{data?.items[0].content}</div>;
};

export default Page;
```

You can generate the `listByType` query using the following command:

```sh
npx ampx generate graphql-client-code
```

**Comment by iartemiev** [comment] 2024-07-19 10:42
Hey @sevenkkk, we just released a bug fix for this issue. Please run the following to update the dependency in your project:
```sh
npm update @aws-amplify/data-schema
```

**Closed by iartemiev** 2024-07-19 10:42 UTC
Labels: bug, Gen 2, data-schema
