### ISSUE TITLE
[Amplify Gen2 Data Schema] Expression produces a union type that is too complex to represent

### ISSUE THREAD

**Issue by ggj0418** [aws-amplify/amplify-category-api#2678] opened 2024-07-01 01:59 UTC
### Environment information

```plain text
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

npx ampx info
System:
  OS: Windows 11 10.0.22631
  CPU: (32) x64 13th Gen Intel(R) Core(TM) i9-13900K
  Memory: 108.03 GB / 127.78 GB
Binaries:
  Node: 20.10.0 - C:\Program Files\nodejs\node.EXE
  Yarn: 1.22.19 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
  npm: 10.8.1 - ~\GolandProjects\my-project\node_modules\.bin\npm.CMD
  pnpm: undefined - undefined
NPM Packages:
  @aws-amplify/backend: 1.0.4
  @aws-amplify/backend-cli: 1.1.0
  aws-amplify: 6.3.8
  aws-cdk: 2.147.1
  aws-cdk-lib: 2.147.1
  typescript: 5.5.2
AWS environment variables:
  AWS_NODEJS_CONNECTION_REUSE_ENABLED = 1
  AWS_SDK_LOAD_CONFIG = 1
  AWS_STS_REGIONAL_ENDPOINTS = regional
```

### Description

# Error Message
`Expression produces a union type that is too complex to represent`

# When that error is occurred
I previously had about 20 data models. In that state, the project build worked normally. However, when I tried to add a new data model, the error is occurring during the build process.

# How I did it
this is my data model schemes.

```typescript
const schema = a.schema({
  TestModel1,
  TestModel2,
  TestModel3,
  TestModel4,
  TestModel5,
  TestModel6,
  TestModel7,
  TestModel8,
  TestModel9,
  TestModel10,
  TestModel11,
  TestModel12,
  TestModel13,
  TestModel14,
  TestModel15,
  TestModel16,
  TestModel17,
  TestModel18,
  TestModel19,
  TestModel20,
  TestModel21,  // When i tried to add this model, project build was failed.
  customQuery1: a
    .query()
    ...
  customQuery2: a
    .query()
    ...
  customQuery3: a
    .query()
    ...
  customQuery4: a
    .query()
    ...
  customQuery5: a
    .query()
    ...
  customQuery6: a
    .query()
    ...
  customQuery7: a
    .query()
    ...
  customQuery8: a
    .query()
    ...
  customQuery9: a
    .query()
    ...
  customQuery10: a
    .query()
    ...
})
```

and each model looks like this
```typescript
export const TestModel1 = a
  .model({
    name: a.string(),
    code: a.string(),
    description: a.string(),
    country: a.string(),
    state: a.string(),
    city: a.string(),
    address: a.string(),
    subAddress: a.string(),
    buildingName: a.string(),
    testModel2s: a.hasMany('TestModel2', 'testModel1Id'),
    .... // other many relationship definitions
  })
  .authorization((allow) => [
    allow.authenticated().to(['read']),
    allow.guest().to(['read'])
  ])
```

and this is the part having that error message.

```typescript
import { generateClient } from 'aws-amplify/data'
import { Schema } from '@/amplify/data/resource'

/**
 * Client for user authentication mode
 */
export const userClient = generateClient<Schema>({ authMode: 'userPool' })

// on this following have that error exactly.
const { data, errors, extensions } = await userClient.models.testModel1.list({})
```

is there any way to solve this problem?

**Comment by dpilch** [comment] 2024-07-01 20:03
Does each of your models have a `hasMany` relationship with all of your other models?

**Comment by ggj0418** [comment] 2024-07-02 02:11
@dpilch yes, some models have a `hasMany` relationship

**Comment by ggj0418** [comment] 2024-07-02 06:49
I put `@ts-ignore` annotation on all the `userClient` and `selectionSet` parts I use, which fixed the build error. And my `IDE (WebStorm, VSC)` was incredibly slow before I put that annotation, but after I put it on, the indexing speed became very fast. Although it was temporarily resolved, I want to find a fundamental solution because it is a solution that eliminates the reason for using typescript.

**Comment by dpilch** [comment] 2024-07-02 15:10
This is likely due to the large number of relationships between the models. The TypeScript engine is having trouble to calculate the types. Adding `@ts-ignore` would circumvent this.

A proper solution will require performance improvements to the data schema builder.

**Comment by ggj0418** [comment] 2024-07-03 02:46
@dpilch Thanks for your answer!

Then, using [Custom Amplify Graphql API Construct](https://constructs.dev/packages/@aws-amplify/graphql-api-construct/v/1.8.0-z-data-schema-generator.0?lang=typescript) could be a solution rather than using amplify's `import { a } from '@aws-amplify/backend'`?

**Comment by dpilch** [comment] 2024-07-03 14:29
That could be an option. You will not get all the TypeScript features on the client side if you choose to not use the data schema builder.

You can also use a string GraphQL SDL schema in `defineData` if you like. The docs have not been released for this yet, but you can see the PR here: https://github.com/aws-amplify/docs/pull/7793

The team is working on optimizations that should prevent the error you are seeing. I can't share the PR because it is in a private repo, but the improvement should be available sooner rather than later.

**Comment by ggj0418** [comment] 2024-07-03 14:30
@dpilch I understand about the situation, thank you for your good reply!

**Comment by chrisbonifacio** [comment] 2024-07-09 18:25
Hi @ggj0418 This seems to be a duplicate of another issue recently opened. Please track this one for updates: https://github.com/aws-amplify/amplify-category-api/issues/2592

**Closed by chrisbonifacio** 2024-07-09 18:25 UTC
Labels: question, transferred, Gen 2, data-schema
