### ISSUE TITLE
Deployment failed: MissingRequiredParameter: Missing required key 'functionId' in params

### ISSUE THREAD

**Issue by cabcookie** [aws-amplify/amplify-category-api#2307] opened 2024-02-27 08:50 UTC
### Environment information

```plain text
System:
  OS: macOS 14.3.1
  CPU: (10) arm64 Apple M1 Pro
  Memory: 112.33 MB / 32.00 GB
  Shell: /bin/zsh
Binaries:
  Node: 18.19.0 - ~/.nvm/versions/node/v18.19.0/bin/node
  Yarn: undefined - undefined
  npm: 10.2.3 - ~/.nvm/versions/node/v18.19.0/bin/npm
  pnpm: undefined - undefined
NPM Packages:
  @aws-amplify/backend: 0.12.1
  @aws-amplify/backend-cli: 0.11.1
  aws-amplify: 6.0.16
  aws-cdk: 2.126.0
  aws-cdk-lib: 2.126.0
  typescript: 5.3.3
AWS environment variables:
  AWS_STS_REGIONAL_ENDPOINTS = regional
  AWS_NODEJS_CONNECTION_REUSE_ENABLED = 1
  AWS_SDK_LOAD_CONFIG = 1
No CDK environment variables
```

### Description

Hello, I run into an issue with my sandbox environment. It happened twice to me in the last 2 weeks and I had to delete and recreate my sandbox which has been quite cumbersome (including recreation of demo data).
I login to my account using SSO and the profile org-data-amplify. My session is valid for a couple of hours and then I need to sign in again. Yesterday, I launched my sandbox environment with `npx amplify sandbox --profile org-data-amplify` and forgot to stop it. So, today I got back to VS Code (I didn't restart it) and stopped the sandbox and ran the command again. Now, I tried to make a change to my data model. I changed my Activity schema from
```javascript
const schema = a.schema({
  Context: a.enum(["family", "hobby", "work"]),
  Activity: a
    .model({
      owner: a.string().authorization([a.allow.owner().to(["read", "delete"])]),
      notes: a.string(),
      finishedOn: a.datetime(),
    })
    .authorization([a.allow.owner()]),
});
```

to
```javascript
const schema = a.schema({
  Context: a.enum(["family", "hobby", "work"]),
  Activity: a
    .model({
      owner: a.string().authorization([a.allow.owner().to(["read", "delete"])]),
      notes: a.string(),
      slateNotes: a.string(),
      finishedOn: a.datetime(),
    })
    .authorization([a.allow.owner()]),
});
```

Amplify identified correctly a file update, synthesized the template and tried to deploy the update but then failed with the mentioned error message. Here is the output in my console:
[Sandbox] Triggered due to a file update event: /Users/carskoch/Development/personal-crm/amplify/data/resource.ts

✨  Synthesis time: 3.86s

⚠️ The --hotswap and --hotswap-fallback flags deliberately introduce CloudFormation drift to speed up deployments
⚠️ They should only be used for development - never use them for your production Stacks!

amplify-personalcrm-carskoch-sandbox-63e4bb09d0: deploying... [1/1]

✨ hotswapping resources:
   ✨ AWS::AppSync::FunctionConfiguration 'MutationcreateActivityauth0Function'
   ✨ AWS::AppSync::FunctionConfiguration 'MutationupdateActivityauth0Function'
   ✨ AWS::AppSync::GraphQLSchema 'uevvie4lgje2pegsontu5uvbwaGraphQLSchema'
   ✨ Contents of S3 Bucket 'amplify-personalcrm-carsk-amplifydataamplifycodege-8slq063fvosf'

✨ Contents of S3 Bucket 'amplify-personalcrm-carsk-amplifydataamplifycodege-8slq063fvosf' hotswapped!
✨ AWS::AppSync::GraphQLSchema 'uevvie4lgje2pegsontu5uvbwaGraphQLSchema' hotswapped!
The CloudFormation deployment has failed. Find more information in the CloudFormation AWS Console for this stack.
Caused By: ❌ Deployment failed: MissingRequiredParameter: Missing required key 'functionId' in params

It mentions I should verify CloudFormation. However, CloudFormation is not showing any events.
How can I fix this issue?

**Comment by AnilMaktala** [comment] 2024-03-04 13:44
Hey @cabcookie, We aim to explore this issue further. Could you possibly join a call with us to delve deeper into the issue?

**Comment by AnilMaktala** [comment] 2024-05-17 15:31
Hey @cabcookie,  Are you still facing this issue in the latest version?

**Comment by pkubat** [comment] 2024-05-21 16:45
@AnilMaktala See this issue with   
    "@aws-amplify/backend": "^1.0.2", 
    "@aws-amplify/backend-cli": "^1.0.3",

**Comment by cabcookie** [comment] 2024-05-21 18:12
I saw this issue again today in my sandbox environment. Had to delete and recreate it. I am using the versions mentioned by @pkubat

**Comment by asanobm** [comment] 2024-05-22 10:24
<img width="930" alt="image" src="https://github.com/aws-amplify/amplify-category-api/assets/38549104/1a92ca48-6f84-4267-8836-8d1a8f658b97">


... this?

**Comment by cabcookie** [comment] 2024-05-22 21:40
Yes exactly @asanobm

**Comment by asanobm** [comment] 2024-05-22 22:13
@cabcookie 

Yes, I've had that same experience multiple times. In the end, the only solutions were either to recreate the sandbox or reset the data structure to its original state and try again.

I apologize for not being of much help. It seems like there might be a bug. It would be a good idea to create a bug report.

```bash
npx ampx info
System:
  OS: macOS 14.4.1
  CPU: (10) arm64 Apple M1 Max
  Memory: 22.71 GB / 64.00 GB
  Shell: /bin/zsh
Binaries:
  Node: 18.20.2 - ~/.nodebrew/current/bin/node
  Yarn: undefined - undefined
  npm: 10.8.0 - ~/workspace/fleeklounge/amplify-next-template/node_modules/.bin/npm
  pnpm: undefined - undefined
NPM Packages:
  @aws-amplify/backend: 1.0.2
  @aws-amplify/backend-cli: 1.0.3
  aws-amplify: 6.3.2
  aws-cdk: 2.142.0
  aws-cdk-lib: 2.142.0
  typescript: 5.4.5
AWS environment variables:
  AWS_STS_REGIONAL_ENDPOINTS = regional
  AWS_NODEJS_CONNECTION_REUSE_ENABLED = 1
  AWS_SDK_LOAD_CONFIG = 1
No CDK environment variables
```

**Comment by asanobm** [comment] 2024-05-24 04:42
@cabcookie 

Hello. The same error occurred today as well. After trying various methods, I updated the amplify CLI and it seems to have resolved the issue.

<img width="707" alt="image" src="https://github.com/aws-amplify/amplify-category-api/assets/38549104/0769bbd0-70ee-45db-998b-a57c0796bc66">

**Comment by LukaASoban** [comment] 2024-05-30 23:05
@asanobm I seem to have gotten the same error today as well. Updating didn't seem to help.

**Comment by JDMathew** [comment] 2024-06-12 22:11
I'm also bumping into this issue on:
"@aws-amplify/backend": "^1.0.2",
"@aws-amplify/backend-cli": "^1.0.3",

**Comment by kekami** [comment] 2024-06-13 20:13
Also running into this issue

**Comment by jewells07** [comment] 2024-06-19 16:08
![image](https://github.com/aws-amplify/amplify-category-api/assets/54440548/a4da4021-02de-4611-b745-5a362fac3323)
I got the same error. I reverted back to where there was no error, ran the sandbox command, and then I changed again. It worked for me. It was a weird behavior, but just give it a try.

**Comment by treewhopper** [comment] 2024-07-03 09:57
also seeing this issue with:
"@aws-amplify/backend": "1.0.4",
"@aws-amplify/backend-cli": "1.1.0",

**Comment by wavegate** [comment] 2024-07-04 16:49
Encountering this after schema modifications. I have to delete and re-seed my sandbox

**Comment by cabcookie** [comment] 2024-07-05 15:05
Over the past 2 weeks. I ran into the issue multiple times. I couldn't find another solution than destroying my sandbox environment and creating a new one. I am running these versions right now:

```
System:
  OS: macOS 14.5
  CPU: (10) arm64 Apple M1 Pro
  Memory: 148.27 MB / 32.00 GB
  Shell: /bin/zsh
Binaries:
  Node: 18.19.0 - ~/.nvm/versions/node/v18.19.0/bin/node
  Yarn: undefined - undefined
  npm: 10.2.3 - ~/.nvm/versions/node/v18.19.0/bin/npm
  pnpm: undefined - undefined
NPM Packages:
  @aws-amplify/backend: 1.0.3
  @aws-amplify/backend-cli: 1.0.4
  aws-amplify: 6.3.4
  aws-cdk: 2.144.0
  aws-cdk-lib: 2.144.0
  typescript: 5.4.5
AWS environment variables:
  AWS_STS_REGIONAL_ENDPOINTS = regional
  AWS_NODEJS_CONNECTION_REUSE_ENABLED = 1
  AWS_SDK_LOAD_CONFIG = 1
No CDK environment variables
```

Will update packages and try again.

**Comment by amalhub** [comment] 2024-07-19 15:42
I ran into this issue as well. In my case, I renamed an existing table field, and this error happened. 
Had to delete the sandbox and regenerate.

**Comment by flowstatedivers** [comment] 2024-07-25 18:33
+1

As a result of a development process I've simply added an extra attribute to an already deployed model definition which resulted in above error. Even tho it's relatively easy to solve this in your sandbox as you remove then re-create your table but what would be a workaround in production type environment without losing data? Is this ever going to be fixed ?

**Comment by nhilbert** [comment] 2024-08-07 18:29
Same here, added an attribute to my model, now the sandbox does not deploy anymore. Second time today.  Hope this will get a fix soon.

**Comment by treewhopper** [comment] 2024-08-07 22:31
> Same here, added an attribute to my model, now the sandbox does not deploy anymore. Second time today. Hope this will get a fix soon.

Have you tried running your `npx amplify sandbox` with `--debug`? I've learned that this function error is very generic, and in my case I was able to get the details I needed to find the underlying issue by adding `--debug`. Good luck!

**Comment by AnilMaktala** [comment] 2024-08-08 15:24
I was able to reproduce the issue after restarting the sandbox and making changes to the model.
<img width="892" alt="image" src="https://github.com/user-attachments/assets/a796099b-23db-4dad-bbd0-29358690ff05">

**Comment by OperationalFallacy** [comment] 2024-08-10 21:50
Run into this as well

I've removed "read" permission in auth rule and it started to fail with this functionId error

`      .authorization((allow) => [allow.owner().to("read")])`

I'm not using amplify cli for deployments. I couldn't make it work for more standard "environments", rather than ephemeral sandboxes. It was conflicting with some environment-specific CDK resources. 

So the deployment still works with a full deployment cycle, when CDK CLI has no `hotswap` and `direct` options. After a full update it can do hotswap again

If anybody wants to try it, this is the cdk command I'm using

cdk deploy --ci --all --output .amplify/artifacts/cdk.out --context amplify-backend-namespace=yourAmplifyAppId --context amplify-backend-name=master --require-approval never --context amplify-backend-type=branch --profile YourAwsSSOProfile-dev --hotswap-fallback --method=direct --watch --context secretLastUpdated=1718888347200 --debug

**Comment by cabcookie** [comment] 2024-08-14 06:05
Calling the sandbox with  `npx ampx sandbox --debug` was a helpful hint. I even added a `JSON.stringify(...)` [1] to the `./node_modules/aws-cdk/lib/index.js` as the error message `Missing required key "functionId" in params` wasn't so helpful. The error comes up very randomly when I add a property in my table. I can't figure out what type of changes is causing the issue as the error messages are not providing enough details even in `--debug` mode. With the `JSON.stringify(...)` I added to the cdk code, I saw that one of the mutation functions of the model I changed was causing the error. This issue happens to me at least once a week. Now, at least I realized I can fix the issue without destroying the whole sandbox by just dropping this particular table and adding it to the schema again afterwards. Still I have to reproduce the data of that table and maybe the tables it has relations with but not the entire sandbox which is less time-consuming.

@treewhopper can you explain a bit how you identified the issue using the debug function? It might be super helpful to reproduce the error and fix it in my environment when it comes up or for the Amplify team to fix it entirely.


[1]
In the `aws-cdk/lib/index.js` I searched for this code
`this.fail("MissingRequiredParameter","Missing required key '"+paramName+"' in "+context)`
and changed it to this
`this.fail("MissingRequiredParameter","Missing required key '"+paramName+"' in "+context+": "+JSON.stringify({shape,params,context}))`
to get more details on the error.

**Comment by svidgen** [comment] 2024-08-19 20:20
I haven't been able to repro this either. Can folks who have been able to repro confirm that they have completely wiped `node_modules`, updated to latest versions of all amplify libs, and are still seeing the issue?

**Comment by dan-whitehouse** [comment] 2024-08-20 17:36
Just wanted to comment and say that I was having the same issue as everyone else. 

> failed: MissingRequiredParameter: Missing required key 'functionId'

I added a new field to the Composer model.
```js
Composer: a
	.model({
		id: a.id().required(),
		editionId: a.id().required(),
		name: a.string().required(),
		birthDate: a.string(),
		deathDate: a.string(),
		sex: a.string(),
		gender: a.string(),
		race: a.string(), //<--- This Field Was Added
		country: a.string(),
		//relationships && special aws data
		sectionEntries: a.hasMany('SectionEntryComposer', ['composerId', 'composerEditionId']),
		sectionEntryContents: a.hasMany('SectionEntryContentComposer', ['composerId', 'composerEditionId']),
		books: a.hasMany('BookComposer', ['composerId', 'composerEditionId']),
		createdAt: a.datetime(),
		updatedAt: a.datetime(),
	})
	.identifier(['id', 'editionId'])
	.secondaryIndexes((index) => [
		index("editionId").queryField("listComposersByEditionId"),
	])
	.authorization(allow => [
		allow.groups(['dev', 'admin']),
		allow.groups(['staff']).to(['create', 'read', 'update']),
		allow.authenticated().to(['read']),
	]),
	
batchCreateComposers: a
	.mutation()
	.arguments({
		editionId: a.id().required(),
		items: a.json().required(),
	})
	.authorization(allow => [
		allow.authenticated(),
	])
	.handler(a.handler.custom({
		entry: './batch-create/Composer.js',
		dataSource: a.ref('Composer'),
	}))
	.returns(a.json()),
```

Oddly enough, the table did update (I checked in DynamoDB), however, when I tried to run the listComposers query, it would tell me that the 'race' field I added (and could see in DynamoDB) didn't exist.


Anyway, these were my initial dependencies.
```json
"devDependencies": {
    "@aws-amplify/backend": "^1.0.4",
    "@aws-amplify/backend-cli": "^1.2.2",
    "aws-cdk": "^2.151.0",
    "aws-cdk-lib": "^2.151.0",
    "constructs": "^10.3.0"
}
```

And I updated them to:
```json 
"devDependencies": {
    "@aws-amplify/backend": "^1.0.5",
    "@aws-amplify/backend-cli": "^1.2.3",
    "aws-cdk": "^2.153.0",
    "aws-cdk-lib": "^2.153.0",
     "constructs": "^10.3.0"
}
```

I reran the sandbox, and it seemed to work.

[DEBUG] 2024-08-20T16:51:33.285Z:
```json
{
    "compilerOptions": {
        "target": "es2022",
        "module": "es2022",
        "moduleResolution": "bundler",
        "resolveJsonModule": true,
        "esModuleInterop": true,
        "forceConsistentCasingInFileNames": true,
        "strict": true,
        "skipLibCheck": true,
        "paths": {
            "$amplify/*": [
                "../.amplify/generated/*"
            ]
        },
        "allowSyntheticDefaultImports": true,
        "resolvePackageJsonExports": true,
        "resolvePackageJsonImports": true,
        "useDefineForClassFields": true,
        "noImplicitAny": true,
        "noImplicitThis": true,
        "strictNullChecks": true,
        "strictFunctionTypes": true,
        "strictBindCallApply": true,
        "strictPropertyInitialization": true,
        "alwaysStrict": true,
        "useUnknownInCatchVariables": true
    },
    "files": [
        "./backend.ts",
        "./auth/resource.ts",
        "./auth/post-confirmation/handler.ts",
        "./auth/post-confirmation/resource.ts",
        "./data/resource.ts",
        "./data/add-user-to-group/handler.ts",
        "./data/add-user-to-group/resource.ts",
        "./data/remove-user-from-group/handler.ts",
        "./data/remove-user-from-group/resource.ts"
    ]
}
```

I'm not sure if the issue still persists, but the next time I make a change, I'll come back and update this comment.

**Comment by ngmeyer** [comment] 2024-08-21 04:22
I still see this issue.  Please see https://github.com/aws-amplify/amplify-category-api/issues/2770 for details on my reproduction.

**Comment by diguini** [comment] 2024-08-28 02:40
It happened to me today.
![image](https://github.com/user-attachments/assets/1898c1e3-e414-4aa8-b8bd-9bfdc0f0d73a)

I just added `allow.authenticated().to(['create'])` to one of my tables.

**Comment by AnilMaktala** [comment] 2024-08-30 15:39
Hey @cabcookie, Thank you for providing the additional information. We are actively investigating this issue and will update the ticket as soon as we have a resolution.

**Comment by dpilch** [comment] 2024-09-05 17:08
I've been investigating this issue trying to find the root cause. It appears the issue only affects models with group or owner auth. If you have any other findings please to continue to update this issue.

**Comment by OperationalFallacy** [comment] 2024-09-10 16:03
> The current work around is to recreate the sandbox or remove the table causing the issue and then restore the table. We recognize that this workaround isn't ideal and we are continuing to investigate the root cause.

A better workaround is to update stack without hotswap option, which fixes the problem and then hot swaps continue to work, I described above. However, amplify doesn't expose that functionality via native CDK to the users, which I think is a missing feature.

If users had option to make cdk updates via native cdk cli, it'd opened additional options for development. My use case is a permanent dev environments. I have some extra resources that take forever to create (dns, ses, acm), thus default amplify sandboxes is not ideal.

I would make native use of cdk cli official, there is not much to configure. The only real problem is credential update time cycle.

**Comment by thomasoehri** [comment] 2024-09-11 08:32
When i run into this issue it is enough to just comment out one of my custom resolvers, deploy, add it back in and deploy again instead of removing a table or even recreating the sandbox, which is much more cumbersome.

**Comment by AnilMaktala** [comment] 2024-09-20 18:06
Hi @cabcookie and @thomasoehri , This issue has been resolved in https://github.com/aws/aws-cdk/releases/tag/v2.159.0 version. Please upgrade your lib to v2.159 version and let us know the results.

**Closed** 2024-10-01 01:09 UTC
Labels: bug, pending-response, transferred, Gen 2, data-schema
