### ISSUE TITLE
API Gateway DEFAULT_4XX and DEFAULT_5XX gateway response setting disappears from time to time

### ISSUE THREAD

**Issue by hisham** [aws-amplify/amplify-category-api#30] opened 2022-05-12 17:23 UTC
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

14.17.16

### Amplify CLI Version

8.1.0

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

no

### Amplify Categories

api

### Amplify Commands

push

### Describe the bug

This is a continuation of https://github.com/aws-amplify/amplify-cli/issues/9540

Today I discovered our API Gateway "Gateway Response" setting has been unset, and was causing users issues. 

See screenshot below. We have not made any recent changes to our Rest API settings. What could be causing this? 

<img width="1235" alt="API Gateway 2022-05-12 10-45-24" src="https://user-images.githubusercontent.com/81853/168131369-d430aedd-b854-4ac8-9450-8655a0bb7556.png">

amplify push --force does not change anything. 

### Expected behavior

API Gateway should respect cloudformation settings

### Reproduction steps

Not sure how to repro. 

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by josefaidt** [comment] 2022-05-25 20:24
Hey @hisham apologies for the delay here! I have not been able to reproduce this issue across various projects and settings changes. Are there any overrides applied by chance?

**Comment by hisham** [comment] 2022-05-26 02:45
Hi @josefaidt - no I don't have overrides for the API category.

**Comment by josefaidt** [comment] 2022-06-13 18:29
Hey @hisham apologies for the delay here!! I was able to reproduce this issue and am actively investigating further

in my API's `build/apibbc1adce-cloudformation-template.json` file
```json
"apibbc1adceDefault4XXResponse": {
      "Type": "AWS::ApiGateway::GatewayResponse",
      "Properties": {
        "ResponseType": "DEFAULT_4XX",
        "RestApiId": {
          "Ref": "apibbc1adce"
        },
        "ResponseParameters": {
          "gatewayresponse.header.Access-Control-Allow-Origin": "'*'",
          "gatewayresponse.header.Access-Control-Allow-Headers": "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'",
          "gatewayresponse.header.Access-Control-Allow-Methods": "'DELETE,GET,HEAD,OPTIONS,PATCH,POST,PUT'",
          "gatewayresponse.header.Access-Control-Expose-Headers": "'Date,X-Amzn-ErrorType'"
        }
      }
    },
    "apibbc1adceDefault5XXResponse": {
      "Type": "AWS::ApiGateway::GatewayResponse",
      "Properties": {
        "ResponseType": "DEFAULT_5XX",
        "RestApiId": {
          "Ref": "apibbc1adce"
        },
        "ResponseParameters": {
          "gatewayresponse.header.Access-Control-Allow-Origin": "'*'",
          "gatewayresponse.header.Access-Control-Allow-Headers": "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'",
          "gatewayresponse.header.Access-Control-Allow-Methods": "'DELETE,GET,HEAD,OPTIONS,PATCH,POST,PUT'",
          "gatewayresponse.header.Access-Control-Expose-Headers": "'Date,X-Amzn-ErrorType'"
        }
      }
    },
```

in the API Gateway console 
<img width="1254" alt="image" src="https://user-images.githubusercontent.com/5033303/173418385-09395e9c-1555-4b68-9b21-4273799490d9.png">

This was an older project I have used for different reproductions and it appears it aligns with the issue you have described, where I have a REST API with several unrestricted routes and no overrides in place. Taking a further look at this one 🙂

**Comment by hisham** [comment] 2022-06-13 18:37
oh wow, amazing @josefaidt , thanks for not giving up :).

**Comment by josefaidt** [comment] 2022-06-14 20:16
Hey @hisham while I was not able to pinpoint the reason why these changes are not being applied I was able to come up with reproduction steps for this:

1. create a new project with `amplify init -y`
2. add a REST API with `amplify add api` > REST > create "Hello, World" Lambda
3. push with `amplify push -y`
4. observe default 4xx and 5xx responses are set with CORS headers
5. add another route to the API with `amplify update api` > add another path > create another "Hello, World" Lambda
6. push with `amplify push -y`
7. observe settings are now removed

It is important to note that the `AWS::ApiGateway::GatewayResponse` resources in the REST API's build `cloudformation-template.json` are nearly identical and do not change when adding new routes. Marking as a bug 🙂

**Comment by alharris-at** [comment] 2022-06-29 20:03
I've created a minimal reproduction of this issue outside the scope of Amplify (just writing pure CFN), so it appears this issue is not strictly an Amplify bug. We are engaging the cloudformation team to help identify if this is a corner case in cloudformation, or in api gateway.

**Comment by alharris-at** [comment] 2022-07-19 18:20
The cloudformation team has confirmed this appears to be an issue in their system, and are working on identifying and resolving internally.

**Closed** 2022-09-07 21:54 UTC
Labels: bug, p1, api-rest
