### ISSUE TITLE
DataStore.save() fails when a field used as a partition key is left empty

### ISSUE THREAD

**Issue by justkj7** [aws-amplify/amplify-category-api#1360] opened 2022-06-10 06:09 UTC
### Description

I deployed my stack in remote server already using ```amplify init && amplify push```
However, when DataStore.save() is invoked, it seems local db is updated but db in remote server is not updated correspondingly.

Here is amplify status using the command.

```
$ amplify status

    Current Environment: dev
    
┌──────────┬───────────────┬───────────┬───────────────────┐
│ Category │ Resource name │ Operation │ Provider plugin   │
├──────────┼───────────────┼───────────┼───────────────────┤
│ Api      │ chatservice   │ Update    │ awscloudformation │
└──────────┴───────────────┴───────────┴───────────────────┘

GraphQL endpoint: xxxx
GraphQL API KEY: xxxx

GraphQL transformer version: 2
```

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [X] DataStore
- [ ] Storage

### Steps to Reproduce

1. configure schema.graphql as following
```
type Room @model @auth(rules: [{allow: public}]) {
  id: ID! @index(name: "roomIdOnCreatedAt", sortKeyFields: ["createdAt"], queryField: "roomIdOnCreatedAt")
  name: String!
  Messages: [Message] @hasMany(indexName: "byRoom", fields: ["id"])
  createdAt: AWSDateTime
}

type Message @model @auth(rules: [{allow: public}]) {
  id: ID!
  content: String!
  username: String
  roomID: ID! @index(name: "byRoom", sortKeyFields: ["createdAt"], queryField: "byRoomCreatedAt")
  createdAt: AWSDateTime
}
```

2. Setup amplify client as following
```
class _MyAppState extends State<MyApp> {
  final AmplifyDataStore _dataStorePlugin = AmplifyDataStore(
    modelProvider: ModelProvider.instance,
  );
  final AmplifyAPI _apiPlugin =
      AmplifyAPI(modelProvider: ModelProvider.instance);

  bool _isLoading = true;

  @override
  initState() {
    super.initState();
    _configureAmplify();
  }

  Future<void> _configureAmplify() async {
    // await Amplify.addPlugin(AmplifyAPI()); // UNCOMMENT this line after backend is deployed
    try {
      await Amplify.addPlugins([_dataStorePlugin, _apiPlugin]);

      // Once Plugins are added, configure Amplify
      await Amplify.configure(amplifyconfig);
    } catch (e) {
      print(e);
    }

    setState(() {
      _isLoading = false;
    });
  }
...
```

3. Invoke save()
```
      Room newRoom = Room(
        name: _tfNameController.text,
      );
      await Amplify.DataStore.save(newRoom);
```

4. Check new record saved in remote server

### Platforms

- [X] iOS
- [ ] Android

### Environment

```bash
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.5.3, on macOS 12.4 21F79 darwin-x64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.67.2)
[✓] Connected device (2 available)

• No issues found!
```

### Dependencies

```bash
- cross_file 0.3.3+1 [js meta]
- crypto 3.0.2 [typed_data]
- csslib 0.17.2 [source_span]
- date_time_format 2.0.1
- diffutil_dart 3.0.0
- equatable 2.0.3 [collection meta]
- ffi 1.2.1
- flutter_chat_types 3.2.1 [equatable json_annotation meta]
- flutter_link_previewer 2.6.1 [flutter flutter_chat_types flutter_linkify html http linkify meta url_launcher]
- flutter_linkify 5.0.2 [flutter linkify]
- flutter_plugin_android_lifecycle 2.0.6 [flutter]
- flutter_web_plugins 0.0.0 [flutter js characters collection meta typed_data vector_math]
- html 0.15.0 [csslib source_span]
- http 0.13.4 [async http_parser meta path]
- http_parser 4.0.1 [collection source_span string_scanner typed_data]
- image_picker_android 0.8.4+13 [flutter flutter_plugin_android_lifecycle image_picker_platform_interface]
- image_picker_for_web 2.1.8 [flutter flutter_web_plugins image_picker_platform_interface]
- image_picker_ios 0.8.4+11 [flutter image_picker_platform_interface]
- image_picker_platform_interface 2.5.0 [cross_file flutter http plugin_platform_interface]
- js 0.6.3
- json_annotation 4.5.0 [meta]
- linkify 4.1.0
- meta 1.7.0
- path 1.8.0
- photo_view 0.13.0 [flutter]
- plugin_platform_interface 2.1.2 [meta]
- sky_engine 0.0.99
- source_span 1.8.1 [collection path term_glyph]
- string_scanner 1.1.0 [charcode source_span]
- term_glyph 1.2.0
- typed_data 1.3.0 [collection]
- url_launcher 6.1.2 [flutter url_launcher_android url_launcher_ios url_launcher_linux url_launcher_macos url_launcher_platform_interface url_launcher_web url_launcher_windows]
- url_launcher_android 6.0.14 [flutter url_launcher_platform_interface]
- url_launcher_ios 6.0.14 [flutter url_launcher_platform_interface]
- url_launcher_linux 3.0.1 [flutter url_launcher_platform_interface]
- url_launcher_macos 3.0.1 [flutter url_launcher_platform_interface]
- url_launcher_platform_interface 2.0.5 [flutter plugin_platform_interface]
- url_launcher_web 2.0.7 [flutter flutter_web_plugins url_launcher_platform_interface]
- url_launcher_windows 3.0.1 [flutter url_launcher_platform_interface]
- uuid 3.0.6 [crypto]
- vector_math 2.1.0
```

### Device

iPhone SE - 3rd generation

### OS

iOS 15.5

### CLI Version

8.3.1

**Comment by dpilch** [comment] 2024-07-02 15:40
Duplicate of https://github.com/aws-amplify/amplify-flutter/issues/5050

**Closed by dpilch** 2024-07-02 15:40 UTC
Labels: bug, p3, DataStore
