### ISSUE TITLE
Unauthorized error - Not Authorized to access child on type parent

### ISSUE THREAD

**Issue by yashBrahma** [aws-amplify/amplify-category-api#1352] opened 2023-03-16 04:01 UTC
### Amplify CLI Version

11.0.0

### Question

We have created an entity with hasOne relationship with another table.
And We have written a custom resolver function for authorization.

When we try to query we are getting parent data but for child data, we are getting an Unauthorized error.

Entities - 

```graphql
type Project @model 
@auth(
    rules: [
        { allow: owner, ownerField: "id", operations: [read, create, update, delete], provider: userPools }
    ]
)
{
  id: ID!
  name: String
  teamId
  team: Team @hasOne (fields: ["teamId"])
}

type Team @model 
@auth(
    rules: [
        { allow: owner, ownerField: "id", operations: [read, create, update, delete], provider: userPools }
    ]
)
{
  id: ID!
  name: String!
}
```

If we use the generated listProjects query, how will the child entity, in this case, "Team" get loaded? More specifically the pipeline resolvers for listProject do not contain any logic to tell how to load the child entity - Team. Where is this configuration? 

Also, how are the authorization rules - the preAuth, Auth, and postAuth pipeline functions applied for the child entity - here Team?

**Comment by phani-srikar** [comment] 2023-03-21 04:03
Hi @yashBrahma, thanks for contacting us. I've tried to reproduce the issue with the schema you've provided and don't see any such error when accessing the `team` attached to `project` via a `list` query, as shown below:
```
{
  "data": {
    "listProjects": {
      "items": [
        {
          "_deleted": true,
          "_lastChangedAt": 1679354726729,
          "_version": 2,
          "id": "user1",
          "createdAt": "2023-03-20T23:19:23.767Z",
          "name": "project101",
          "team": {
            "_deleted": null,
            "_version": 1,
            "_lastChangedAt": 1679354155652,
            "createdAt": "2023-03-20T23:15:55.626Z",
            "id": "user1",
            "updatedAt": "2023-03-20T23:15:55.626Z",
            "name": "name101"
          },
          "teamId": "5bbfeb65-997c-4de2-9276-b7401be3ea68::user1",
          "updatedAt": "2023-03-20T23:19:23.767Z"
        }
      ],
      "nextToken": null,
      "startedAt": null
    }
  }
}
```
I suspect there must be some issue with your custom resolver function used for Authorization. Can you share more information about that?

The below summary will give you more insight on how the connected child elements are retrieved:
- We use field level AppSync resolvers to take care of the Authorization and fetching of child element. You can see these named as `Project.team.auth.1` and `Project.team`.

- In the field level Auth function, we construct the user's current claim using format `cognito_identity_sub::cognito_username`. This claim is then matched with the value of `ownerField` which is `teamId` in this case. It is considered a match if `teamId` matches **either** `cognito_identity_sub` or `cognito_username`. 
-- If it's a match, user is Authorized. 
-- Else, we check if there's any preset `authFilter` in the context object by the previous slots.
-- If there's no `authFilter` set as well, the user is un-authorized.

- In the field level data retrieval function, we construct a `GetRequest` against the child DDB table to retrieve the connected `team` using the value of `teamId` present on the parent. 

- There are similar checks also present for the `list` query operation as a whole which you can check it out inside the `Query.listProjects.<pre/post>auth` functions. Find more about order of execution of these slots [here](https://docs.amplify.aws/cli/graphql/custom-business-logic/#supported-resolver-slots).

**Comment by yashBrahma** [comment] 2023-03-21 05:19
Hi @phani-srikar, thanks for the response.

I above case will for generated resolvers. We have written a custom resolver to list the projects. We have our own Authorization logic written. 

I was able to find the issue and fix it, which was in field-level AppSync resolvers Authorization. Currently, I updated the resolver by adding a resolver file in the **resolvers**  directory. But I want to update it using CDK.

So, can you please give me a solution to how it is updated in CDK?
I tried updating using CDK but it gave me an error saying " Only one resolver is allowed per field."

**Comment by phani-srikar** [comment] 2023-03-21 16:57
Hi @yashBrahma. Thanks for reverting back. We do allow adding a custom resource via CDK as seen in [this doc](https://docs.amplify.aws/cli/graphql/custom-business-logic/#vtl-resolver). But the main use-case for that is when you have a custom query/mutation and want to attach a pipeline resolver to that. Since your use-case is to [override an existing resolver](https://docs.amplify.aws/cli/graphql/custom-business-logic/#override-amplify-generated-resolvers), using the `resolvers` directory is the recommended way. 
I am not sure which pipeline ID are you referring to. Can you please describe it?

**Comment by AnilMaktala** [comment] 2023-05-26 17:09
Hi @yashBrahma 👋, We are closing this issue as we have not received any response from you. However, if you are still facing the same issue and require our assistance, please don't hesitate to leave a comment and provide us with the information our team had previously asked for. This way, we can reopen the issue and provide you with better assistance.

Thank you!

**Closed by AnilMaktala** 2023-05-26 17:09 UTC
Labels: question, pending-triage, pending-response, transferred
