### ISSUE TITLE
Nodejs version no longer supported in autogenerated cloudformation resources 

### ISSUE THREAD

**Issue by zandieh** [aws-amplify/amplify-category-api#1520] opened 2023-05-29 20:23 UTC
### How did you install the Amplify CLI?

npm install -g @aws-amplify/cli

### If applicable, what version of Node.js are you using?

v19.4.0

### Amplify CLI Version

12.0.1

### What operating system are you using?

Ubuntu

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made.

### Describe the bug

I'm using amplify cli to push a custom docker container api resource and from last Friday I'm getting following error:
```
2023-05-29T17:54:01.571Z [INFO]: 🛑 The following resources failed to deploy:
                                 Resource Name: AwaiterCustomEventHandler8B7CBA73 (AWS::Lambda::Function)
                                 Event Type: create
                                 Reason: Resource handler returned message: "The runtime parameter of nodejs12.x is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs18.x) while creating or updating functions. (Service: Lambda, Status Code: 400, Request ID: 7e29dfc4-dff9-4f5c-a1fa-291cd24288b2)" (RequestToken: 6ab2daa5-649b-8020-c9f9-8b263ce1e182, HandlerErrorCode: InvalidRequest)
2023-05-29T17:54:01.581Z [INFO]: Resource Name: PreDeployLambdaF7CAA99F (AWS::Lambda::Function)
                                 Event Type: create
                                 Reason: Resource handler returned message: "The runtime parameter of nodejs12.x is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs18.x) while creating or updating functions. (Service: Lambda, Status Code: 400, Request ID: f9c8a502-0f61-4e9e-9c3f-2aa3899fb0e9)" (RequestToken: 98ebe87f-4c76-1dc6-9d72-31c40e92fd2f, HandlerErrorCode: InvalidRequest)
                                 🛑 Resource is not in the state stackUpdateComplete
                                 Name: PreDeployLambdaF7CAA99F (AWS::Lambda::Function), Event Type: create, Reason: Resource handler returned message: "The runtime parameter of nodejs12.x is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs18.x) while creating or updating functions. (Service: Lambda, Status Code: 400, Request ID: f9c8a502-0f61-4e9e-9c3f-2aa3899fb0e9)" (RequestToken: 98ebe87f-4c76-1dc6-9d72-31c40e92fd2f, HandlerErrorCode: InvalidRequest)
```

when I check the cloudformation template I see following resource is generated by amplify to push resource to ECS container 
```
    "AwaiterCustomEventHandler8B7CBA73": {
      "Type": "AWS::Lambda::Function",
      "Properties": {
        "Code": {
          "ZipFile": "exports.handler = async function({ RequestType, PhysicalResourceId, ResourceProperties }) {\n  switch (RequestType) {\n    case 'Delete':\n    case 'Update':\n      return { PhysicalResourceId };\n  }\n\n  const { pipelineName } = ResourceProperties;\n\n  const result = {\n    PhysicalResourceId: `pipelineawaiter-${pipelineName}`,\n  };\n\n  return result;\n};\n"
        },
        "Role": {
          "Fn::GetAtt": [
            "AwaiterCustomEventHandlerServiceRoleCC4D5DBF",
            "Arn"
          ]
        },
        "Handler": "index.handler",
        "Runtime": "nodejs12.x",
        "Timeout": 15
      },
      "DependsOn": [
        "AwaiterCustomEventHandlerServiceRoleCC4D5DBF"
      ]
    },
```

### Expected behavior

resources should be generated by   nodejs18.x

### Reproduction steps

1. create restful docker container custom api

```
? Select from one of the below mentioned services: REST
? Which service would you like to use API Gateway + AWS Fargate (Container-based)
? Provide a friendly name for your resource to be used as a label for this category in the project: testapi
? What image would you like to use Custom (bring your own Dockerfile or docker-compose.yml)
? When do you want to build & deploy the Fargate task On every "amplify push" (Fully managed container source)
? Do you want to access other resources in this project from your api? Yes
? Select the categories you want this function to have access to. api, auth, function, storage
```

### Log output

<details>

```
# Put your logs below this line


```

</details>
[amplify-cli-2023-05-29.log](https://github.com/aws-amplify/amplify-cli/files/11594001/amplify-cli-2023-05-29.log)

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by josefaidt** [comment] 2023-05-30 18:47
I was able to reproduce this issue using the following steps:

1. `amplify init -y`
2. `amplify configure project` > Enable container-based deployments
3. `amplify add api` > REST > choose the Fargate option
4. `amplify push`
5. observe error

After running `amplify push` the CLI will rewrite this file, therefore we are not able to modify this template to bump the Node version of this Lambda from `node12.x` to `node16.x`/`node18.x`

Marking as a bug

**Comment by jjrdevspace01** [comment] 2023-05-31 21:18
this seems to affect amplify deployments if you run 'amplify update auth' and then start deployment via amplify console - tried to make MFA optional and got it on MFALambda - even after turning that back to off we have it on UpdateRolesWithIDPFunction. same message on both`The runtime parameter of nodejs12.x is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs18.x) while creating or updating functions.`  unable to deploy amplify project as a result

**Comment by mck782** [comment] 2023-06-01 21:42
Is there any workaround while the bug is getting fixed?

**Comment by fossamagna** [comment] 2023-06-07 03:55
Workaround: use version `12.1.0-rc.2def814808.0`.

```
npm i -g @aws-amplify/cli@12.1.0-rc.2def814808.0
```

 https://www.npmjs.com/package/@aws-amplify/cli/v/12.1.0-rc.2def814808.0

**Comment by chrislrobert** [comment] 2023-06-07 10:16
@Kaiki-kk @fossamagna THANK YOU! Will try ASAP. Really appreciate it.

**Comment by zandieh** [comment] 2023-06-08 22:37
The rc build doesn't work for me! I'm getting following error during push after upgrading the amplify version:


```
🛑 statement.freeze is not a function

Learn more at: https://docs.amplify.aws/cli/project/troubleshooting/

Session Identifier: 8645920b-d6f4-42d0-ace0-c160b5d3dab8
```

**Comment by fossamagna** [comment] 2023-06-10 23:37
@chrislrobert @zandieh 
FYI, I opened PR #1556 to fix #1445. I hope that it is reviewed and it is merged quickly.

**Comment by chrislrobert** [comment] 2023-06-11 00:04
> @chrislrobert @zandieh FYI, I opened PR #1556 to fix #1445. I hope that it is reviewed and it is merged quickly.

Thanks, @fossamagna !

**Comment by zandieh** [comment] 2023-06-12 15:33
Thanks @fossamagna !

**Comment by alharris-at** [comment] 2023-07-14 23:11
Thank you for the contribution @fossamagna, we've merged the change, and will cut a release of the Amplify API Category now, to flow into an upcoming CLI version.

**Comment by alharris-at** [comment] 2023-07-26 18:11
We are still waiting for these changes to be available on the `@aws-amplify/cli@latest` tag, I've cut a tagged release to temporarily unblock folks. In order to use this pre-release version, you can follow the steps below.

```sh
# Install Tagged Release with REST API Bug Fixes
`npm i -g @aws-amplify/cli@rest-api-july-temp`

# Confirm Version is in use
`> amplify --version` # 12.2.2-rest-api-july-temp.0
```

I've confirmed that I can deploy a containerized-REST api, which has access to a ddb table, and that the deployed app works for CRUD functionality via this app https://github.com/alharris-at/container-wiring-test

**Comment by malcomm** [comment] 2023-08-10 19:48
+1

**Comment by alharris-at** [comment] 2023-10-31 15:20
Closing this issue, since this should have been mitigated since Amplify CLI version 12.3.0 and up.

**Closed by alharris-at** 2023-10-31 15:20 UTC
Labels: bug, p1, transferred, containers, theme:platform-upgrades
