### ISSUE TITLE
Can't use `add-graphql-datasource` command with Amplify CLI@8.2.0

### ISSUE THREAD

**Issue by sasssssssa** [aws-amplify/amplify-category-api#481] opened 2022-05-18 06:27 UTC
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### Amplify CLI Version

8.2.0

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No

### Amplify Categories

api

### Amplify Commands

add

### Describe the bug

We can't use `add-graphql-datasource` command even if I set `'transformerVersion': 1` in cli.json.
Also, I checked  we was able to use `add-graphql-datasource` command with Amplify CLI@7.6.26.

Could you fix this bug for being able to use `add-graphql-datasource` command with latest Amplify CLI?

command output
```
$ amplify api add-graphql-datasource
Using datasource: Aurora Serverless, provided by: awscloudformation
🛑 There was an error adding the datasource
🛑 File at path: '.../amplify/#current-cloud-backend/awscloudformation/build/undefined' does not exist
$ amplify --version
8.2.0
```

cli.json
```
{
  "features": {
    "graphqltransformer": {
      "addmissingownerfields": true,
      "improvepluralization": false,
      "validatetypenamereservedwords": true,
      "useexperimentalpipelinedtransformer": true,
      "enableiterativegsiupdates": true,
      "secondarykeyasgsi": true,
      "skipoverridemutationinputtypes": true,
      "suppressschemamigrationprompt": true,
      "useExperimentalPipelinedTransformer":false,
      "transformerversion": 1
      ...
```

Thanks

### Expected behavior

We can add datasource with latest Amplify CLI when we set `'transformerVersion': 1` in cli.json and do `add-graphql-datasource` command

### Reproduction steps

1. Set `'transformerVersion': 1` in cli.json.
2. Do `add-graphql-datasource` command

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by BBopanna** [comment] 2022-07-19 09:14
Ditto on the issue - why does Amplify team release features without backwards compatibility. We have moved on the V2 of the graphQL transformer and now have to deal with this short coming.

@ErikCH  - Can you please have someone take a look at this.

**Comment by rodfferreira** [comment] 2022-08-03 18:59
Hi,
I have made the above changes to the files as proposed by @josefaidt and in my modified @8.2.0 version everything works fine.

Unfortunatelly, I am  still getting an error when trying to pull the environment with newer versions (I've just tried 9.2.0)
<img width="943" alt="Captura de Tela 2022-08-03 às 15 58 10" src="https://user-images.githubusercontent.com/46480796/182687824-421197e7-be68-4000-906f-ba298b8b616e.png">

**Comment by promentol** [comment] 2022-08-10 06:50
Any updates regarding this issue? I can't use with 9.2.0 amplify cli version

**Comment by nsdhillon1** [comment] 2022-08-17 05:42
I am running into the same issue...

**Comment by nsdhillon1** [comment] 2022-08-26 16:44
Bump..  Any updates on this please?  This is a critical issue that is keeping our dev team from proceeding

**Comment by SantoshRaoMea** [comment] 2022-08-28 06:26
Facing same issue

**Comment by SantoshRaoMea** [comment] 2022-08-28 08:59
Just sharing, i did a work around to bypass this issue
project/amplify/#current-cloud-backend/awscloudformation/build/undefined

I went to the build directory above and copied the root-cloudformation-stack.json to a file called undefined

and i was able to add the data source, just in case it helps anyone

**Comment by rodfferreira** [comment] 2022-09-01 00:58
Any news? We have a big project running on amplify relying on Aurora mysql serverless. I want to upgrade my amplify version, but I cant.

**Comment by Crhis35** [comment] 2022-09-05 23:07
Same issue 9.2.1

**Comment by rodfferreira** [comment] 2022-09-07 02:52
Duplicate of #767

**Comment by aldensully** [comment] 2022-09-09 17:25
Updates on this??

**Comment by anyaokpesten** [comment] 2022-10-14 12:27
it still doesn't work.
amplify -v 
10.2.3

**Comment by sasithwarnakafonseka** [comment] 2022-11-10 11:14
it still doesn't work.
version 10.4.0!

**Comment by tomaseti** [comment] 2022-11-29 20:42
it still doesn't work.
version 10.5.1

**Comment by nsdhillon1** [comment] 2022-12-13 22:05
Any update on this?

**Comment by sundersc** [comment] 2022-12-19 19:20
@anyaokpesten @sasithwarnakafonseka @tomaseti @nsdhillon1 - Sorry about the delay in response. I couldn't reproduce the issue with `^10.5.1`. Do you still see the same error message? Also, could you run `amplify diagnose` command send the project identifier.
https://docs.amplify.aws/cli/reference/diagnose/

**Comment by Crhis35** [comment] 2022-12-19 19:44
Seems to be its working on 10.5.2 also

**Comment by sundersc** [comment] 2022-12-19 20:15
This workflow expects RDS credentials to be stored in the secret manager. Create a new secret in `AWS Secret Manager` and rerun the amplify command.

1. Goto `AWS Console` > Open `Secret Manager`.
2. Click on `Store a new Secret`.
3. Enter the credentials and select the appropriate RDS resource (cluster/instance). Walk through the prompts and save the secret.
4. Rerun the amplify command.

**Comment by sundersc** [comment] 2024-02-21 21:06
Closing the issue due to inactivity. Please reopen if you run into this issue again.

**Closed by sundersc** 2024-02-21 21:06 UTC
Labels: bug, p2, transferred, platform, graphql-transformer-v1
