### ISSUE TITLE
Secondary @index query data not accessible due to not authorize error with graphql gransformerv2

### ISSUE THREAD

**Issue by ingwinlu** [aws-amplify/amplify-category-api#468] opened 2022-01-10 09:53 UTC
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v16

### Amplify CLI Version

7.6.7

### What operating system are you using?

Ubuntu WSL

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

Upgrade to graphql transformer v2

### Amplify Categories

auth, api

### Amplify Commands

Not applicable

### Describe the bug

After upgrading to the new graphql transformer my queries that use secondary indexes can no longer be used by our users as they appear to now be "unauthorized" via dynamic group authorisation.
When executing `farmsByCustomer` I now get
```
  "errors": [
    {
      "path": [
        "farmsByCustomer"
      ],
      "data": null,
      "errorType": "Unauthorized",
      "errorInfo": null,
      "locations": [
        {
          "line": 2,
          "column": 3,
          "sourceName": null
        }
      ],
      "message": "Not Authorized to access farmsByCustomer on type ModelFarmConnection"
    }
  ]
  ```

This seems to not be the case for static group authorisation (role_superadmin still can access the data fine).

All queries were executed via the appsync console to exclude our client code from having any impact on the issue.

### Expected behavior

Users can still access data via custom indexes or instructions on how to allow access to the custom index.

### Reproduction steps

1. old model with expected behaviour (data accessible via gsi)
2. run transform
3. data no longer accessible

### GraphQL schema(s)

<details>

```graphql
type Farm
  @model
  @auth(
    rules: [
      {
        allow: groups
        groups: ["role_superadmin"]
        operations: [create, update, delete, read]
      },
      { allow: groups, groupsField: "customerName", operations: [read] },
      { allow: groups, groups: ["bpe"], operations: [read] },
      { allow: private, provider: iam, operations: [create, read, update] }
    ]
  ) {
  name: String! @primaryKey
  location: String! # europe_austria_vienna -> we can query by BEGINS_WITH to efficiently filter if we put this in a sort key
  type: FarmType
  latitude: Float
  longitude: Float
  weather: Weather
  weatherForecasts: [Weather]
  weatherWarnings: [WeatherWarning]
  customerName: String!
    @index(
      name: "byCustomerName"
      queryField: "farmsByCustomer"
      sortKeyFields: ["location"]
    )
  status: FarmStatus
  customer: Customer @belongsTo(fields: ["customerName"])
  units: [Unit]
    @hasMany(
      indexName: "byCustomerAndFarmName"
      fields: ["customerName", "name"]
    )
}

```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by ykethan** [comment] 2022-05-23 18:37
Hey @menendezjaume, a quick followup on this unauthorized error on Lambda function. I was able to reproduce this issue and has been marked as bug. Please refer to https://github.com/aws-amplify/amplify-cli/issues/10445#issuecomment-1134819106.
The workaround is to add a new line in your schema and push the change.

**Comment by josefaidt** [comment] 2022-06-17 19:05
Closing due to inactivity

**Closed by josefaidt** 2022-06-17 19:05 UTC
Labels: pending-triage, pending-close-response-required

**Comment by sithu951** [comment] 2022-10-10 14:03
Thanks to @aaronkik, I used custom resolver to solve my similar issue. I found a shorter version, using `contains` in place of `foreach`. Please see below:

> ```java
> // ...
> #if( !$util.isNull($ctx.args.teamID) )
>     #set( $teamIDClaim = $util.defaultIfNull($ctx.identity.claims.get("cognito:groups"), "___xamznone____") )
>     #if( $util.isString($ctx.args.teamID) )
>       #set( $teamIDCondition = ($teamIDClaim.contains($ctx.args.teamID)) ) // <--- Here, we change
>     #else
>       #set( $teamIDCondition = ($teamIDClaim == $util.defaultIfNull($ctx.args.teamID.get("eq"), "___xamznone____")) )  // <--- We might also need to change here
>     #end
>     #if( $teamIDCondition )
>       #set( $isAuthorized = true )
>       $util.qr($ctx.stash.put("authFilter", null))
>     #end
>   #else
>     $util.qr($primaryFieldMap.put("teamID", $util.defaultIfNull($ctx.identity.claims.get("cognito:groups"), "___xamznone____")))
>   #end
> // ...
> ```
